### ISSUE TITLE
Conflicting values for setting exception

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6044]
Per a short convo in slack with @cjohnhanson. I was running into this exception:

```
Conflicting values for setting found in: (<generator object BaseEnvStoreManager.get.<locals>.<genexpr> at 0x10508ec10>,)
```

This is in my old catch-all dev project, so the config is pretty messy. But in case its useful, I threw my meltano.yml [in a gist here ](https://gist.github.com/pandemicsyn/ba8a935f441cd9d1a6826cbe21851d80). The exception triggered when I was attempting to start the airflow scheduler. I haven't noticed it triggering any other time.

```
(melty-3.8) ➜  meltano invoke airflow scheduler
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2022-06-06 19:27:33,000] {scheduler_job.py:1266} INFO - Starting the scheduler
[2022-06-06 19:27:33,001] {scheduler_job.py:1271} INFO - Processing each file at most -1 times
[2022-06-06 19:27:33,003] {dag_processing.py:254} INFO - Launched DagFileProcessorManager with pid: 82683
[2022-06-06 19:27:33,003] {scheduler_job.py:1835} INFO - Resetting orphaned tasks for active dag runs
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "airflow.utils.serve_logs" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2022-06-06 19:27:33,206] {_internal.py:113} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
[2022-06-06 19:27:33,275] {settings.py:51} INFO - Configured default timezone Timezone('UTC')
[2022-06-06 19:27:33,278] {dag_processing.py:529} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2 ) when using sqlite. So we set parallelism to 1.
Conflicting values for setting found in: (<generator object BaseEnvStoreManager.get.<locals>.<genexpr> at 0x1093dac10>,)
```

Full traceback:

```
022-06-07T00:28:45.738001Z [debug    ] Conflicting values for setting found in: (<generator object BaseEnvStoreManager.get.<locals>.<genexpr> at 0x105ab2f20>,)
Traceback (most recent call last):
  File "/Users/syn/projects/meltano/src/meltano/cli/__init__.py", line 51, in main
    cli(obj={"project": None})
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/syn/.pyenv/versions/3.8.12/envs/melty-3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/cli/params.py", line 23, in decorate
    return func(*args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/cli/params.py", line 56, in decorate
    func(project, *args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/cli/schedule.py", line 34, in schedule
    ctx.obj["schedule_service"] = ScheduleService(project)
  File "/Users/syn/projects/meltano/src/meltano/core/schedule_service.py", line 66, in __init__
    self.plugins_service = plugins_service or ProjectPluginsService(project)
  File "/Users/syn/projects/meltano/src/meltano/core/project_plugins_service.py", line 81, in __init__
    self.hub_service = hub_service or MeltanoHubService(project)
  File "/Users/syn/projects/meltano/src/meltano/core/hub/client.py", line 106, in __init__
    if self.settings_service.get("send_anonymous_usage_stats"):
  File "/Users/syn/projects/meltano/src/meltano/core/settings_service.py", line 447, in get
    value, _ = self.get_with_source(*args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/core/settings_service.py", line 434, in get_with_source
    value, metadata = self.get_with_metadata(*args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/core/project_settings_service.py", line 156, in get_with_metadata
    value, metadata = super().get_with_metadata(name, *args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/core/settings_service.py", line 365, in get_with_metadata
    value, get_metadata = manager.get(name, setting_def=setting_def)
  File "/Users/syn/projects/meltano/src/meltano/core/settings_store.py", line 1181, in get
    value, metadata = manager.get(name, setting_def=setting_def, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/core/settings_store.py", line 351, in get
    value, metadata = super().get(*args, **kwargs)
  File "/Users/syn/projects/meltano/src/meltano/core/settings_store.py", line 309, in get
    raise ConflictingSettingValueException(
meltano.core.settings_store.ConflictingSettingValueException: Conflicting values for setting found in: (<generator object BaseEnvStoreManager.get.<locals>.<genexpr> at 0x105ab2f20>,)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/syn/projects/meltano/src/meltano/cli/__init__.py", line 59, in main
    raise CliError(str(err)) from err
meltano.cli.utils.CliError: Conflicting values for setting found in: (<generator object BaseEnvStoreManager.get.<locals>.<genexpr> at 0x105ab2f20>,)
```

**Comment by tayloramurphy** [comment]
@pandemicsyn I'm closing this as this specific warning should be addressed in the scope of:

- https://github.com/meltano/meltano/issues/3135
