### ISSUE TITLE
bug: Airflow 1.10.x and 2.1.x broken when upgrading to Meltano 2.0+

### ISSUE THREAD

**Issue by SBurwash** [meltano/meltano#6209]
I'm having issues deploying to production my 2.0.2 version of meltano regarding airflow.

My current version of airflow is 1.10.15 (not 2.X)  and everything works locally, but when I push to production I get this error message:

```
15/06/2022, 11:32:18	[2m2022-06-15T15:32:18.287237Z[0m [[32m[1mdebug [0m] [1mDeleted configuration at /project/.meltano/run/airflow/airflow.cfg[0m	airflow-scheduler
15/06/2022, 11:32:18	[2m2022-06-15T15:32:18.287889Z[0m [[31m[1merror [0m] [1mTraceback (most recent call last):	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/bin/airflow", line 25, in <module>	airflow-scheduler
15/06/2022, 11:32:18	from airflow.configuration import conf	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/__init__.py", line 31, in <module>	airflow-scheduler
15/06/2022, 11:32:18	from airflow.utils.log.logging_mixin import LoggingMixin	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/utils/__init__.py", line 24, in <module>	airflow-scheduler
15/06/2022, 11:32:18	from .decorators import apply_defaults as _apply_defaults	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/utils/decorators.py", line 36, in <module>	airflow-scheduler
15/06/2022, 11:32:18	from airflow import settings	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/settings.py", line 38, in <module>	airflow-scheduler
15/06/2022, 11:32:18	from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG # NOQA F401	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 737, in <module>	airflow-scheduler
15/06/2022, 11:32:18	conf.read(AIRFLOW_CONFIG)	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 425, in read	airflow-scheduler
15/06/2022, 11:32:18	self._validate()	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 217, in _validate	airflow-scheduler
15/06/2022, 11:32:18	self._validate_config_dependencies()	airflow-scheduler
15/06/2022, 11:32:18	File "/project/.meltano/orchestrators/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 249, in _validate_config_dependencies	airflow-scheduler
15/06/2022, 11:32:18	raise AirflowConfigException(	airflow-scheduler
15/06/2022, 11:32:18	airflow.exceptions.AirflowConfigException: error: cannot use sqlite with the LocalExecutor	airflow-scheduler
15/06/2022, 11:32:18	[0m	airflow-scheduler
15/06/2022, 11:32:18	[2m2022-06-15T15:32:18.289815Z[0m [[32m[1mdebug [0m] [1mCommand `airflow --help` failed[0m	airflow-scheduler
15/06/2022, 11:32:18	Traceback (most recent call last):	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/__init__.py", line 55, in _run_cli	airflow-scheduler
15/06/2022, 11:32:18	cli(obj={"project": None})	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__	airflow-scheduler
15/06/2022, 11:32:18	return self.main(*args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main	airflow-scheduler
15/06/2022, 11:32:18	rv = self.invoke(ctx)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke	airflow-scheduler
15/06/2022, 11:32:18	return _process_result(sub_ctx.command.invoke(sub_ctx))	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke	airflow-scheduler
15/06/2022, 11:32:18	return ctx.invoke(self.callback, **ctx.params)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke	airflow-scheduler
15/06/2022, 11:32:18	return callback(*args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/params.py", line 23, in decorate	airflow-scheduler
15/06/2022, 11:32:18	return func(*args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/params.py", line 56, in decorate	airflow-scheduler
15/06/2022, 11:32:18	func(project, *args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/invoke.py", line 139, in invoke	airflow-scheduler
15/06/2022, 11:32:18	raise invoke_err	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/invoke.py", line 123, in invoke	airflow-scheduler
15/06/2022, 11:32:18	exit_code = run_async(	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/utils/__init__.py", line 52, in run_async	airflow-scheduler
15/06/2022, 11:32:18	loop.run_until_complete(future)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete	airflow-scheduler
15/06/2022, 11:32:18	return future.result()	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/invoke.py", line 164, in _invoke	airflow-scheduler
15/06/2022, 11:32:18	async with invoker.prepared(session):	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/async_generator/_util.py", line 34, in __aenter__	airflow-scheduler
15/06/2022, 11:32:18	return await self._agen.asend(None)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/plugin_invoker.py", line 248, in prepared	airflow-scheduler
15/06/2022, 11:32:18	await self.prepare(session)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/plugin_invoker.py", line 223, in prepare	airflow-scheduler
15/06/2022, 11:32:18	async with self.plugin.trigger_hooks("configure", self, session):	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/async_generator/_util.py", line 34, in __aenter__	airflow-scheduler
15/06/2022, 11:32:18	return await self._agen.asend(None)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 87, in trigger_hooks	airflow-scheduler
15/06/2022, 11:32:18	await self.__class__.trigger(self, f"before_{hook_name}", *args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 115, in trigger	airflow-scheduler
15/06/2022, 11:32:18	raise err	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 107, in trigger	airflow-scheduler
15/06/2022, 11:32:18	await hook_func(target, *args, **kwargs)	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/core/plugin/airflow.py", line 121, in before_configure	airflow-scheduler
15/06/2022, 11:32:18	raise AsyncSubprocessError(	airflow-scheduler
15/06/2022, 11:32:18	meltano.core.error.AsyncSubprocessError: Command `airflow --help` failed	airflow-scheduler
15/06/2022, 11:32:18	The above exception was the direct cause of the following exception:	airflow-scheduler
15/06/2022, 11:32:18	Traceback (most recent call last):	airflow-scheduler
15/06/2022, 11:32:18	File "/usr/local/lib/python3.8/site-packages/meltano/cli/__init__.py", line 63, in _run_cli	airflow-scheduler
15/06/2022, 11:32:18	raise CliError(str(err)) from err	airflow-scheduler
15/06/2022, 11:32:18	meltano.cli.utils.CliError: Command `airflow --help` failed	airflow-scheduler
15/06/2022, 11:32:18	Command `airflow --help` failed
```

Here is a link to the complete slack conversation: https://meltano.slack.com/archives/C01TCRBBJD7/p1655303081378359 

Has anyone ever seen this error? My first guess is that it's linked to not being on airflow 2.X, but would appreciate feedback

**Comment by SBurwash** [comment]
I did not change anything from my regular deployment in meltano 1.X Here is relevant airflow files:

In meltano.yml:
```
 orchestrators:
  - name: airflow
    pip_url: psycopg2 apache-airflow==1.10.15 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.8.txt
  files:
  - name: airflow
    pip_url: git+https://gitlab.com/meltano/files-airflow.git
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
```
In infra/task-definitions/meltano.json (paraphrasing)
``` 
For scheduler, webserver and meltano-ui
AIRFLOW__CORE__EXECUTOR = LocalExecutor
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN = postgresurl
MELTANO_DATABASE_URI = other_postgresurl
```

**Comment by DouweM** [comment]
@SBurwash With Airflow 1.10.15, I think you need `AIRFLOW__CORE__SQL_ALCHEMY_CONN` instead of `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN`. Can you see if that works?

**Comment by SBurwash** [comment]
I changed it this morning from core to database and it had no effect

**Comment by DouweM** [comment]
@SBurwash What if you explicitly add the `core.sql_alchemy_conn` setting to `meltano.yml` but still have it reference that env var: (or with core -> database both in the key and the env var)

```yml
orchestrators:
  - name: airflow
    pip_url: psycopg2 apache-airflow==1.10.15 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.8.txt
    config:
      core:
        sql_alchemy_conn: $AIRFLOW__CORE__SQL_ALCHEMY_CONN
```

**Comment by DouweM** [comment]
@SBurwash What if you explicitly add the `core.sql_alchemy_conn` setting to `meltano.yml` but still have it reference that env var: (or with core -> database both in the key and the env var)

```yml
orchestrators:
  - name: airflow
    pip_url: psycopg2 apache-airflow==1.10.15 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.8.txt
    config:
      core:
        sql_alchemy_conn: $AIRFLOW__CORE__SQL_ALCHEMY_CONN
```

**Comment by SBurwash** [comment]
I will get back to you on this; I abandonned for now and am trying to install airflow 2.3.2 instead

**Comment by socketbox** [comment]
I'm in a similar situation and wanted to clarify that Airflow 2.1.2 (which is, afaik, the version Meltano 2.1.0 installs) uses `AIRFLOW__CORE__SQL_ALCHEMY_CONN` and not `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN`. Also, having uninstalled and reinstalled airflow after moving to Meltano 2.1.0, I noticed that there is a `variant` attribute added to the `orchestrator` section:
```
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
```
After moving to Meltano 2.1.0, Airflow seems to completely ignore environment variables and write a config file full of invalid definitions and proceed from there.

**Comment by SBurwash** [comment]
Update: I can't speak to an issue fix, but I dropped my airflow DB and upgraded to 2.3.2 and this fixed all issues

**Comment by DouweM** [comment]
@nickhamlin For each of the following scenarios, can you please share: 1. (the airflow parts of) `meltano.yml` (especially `pip_url` and `config`), 2. any environment variables you're setting, 3. the result of `meltano invoke --dump=config airflow` (with creds edited out), and 4. the exact error message when you run `meltano invoke airflow webserver`?

1. Airflow 2.1.x with `AIRFLOW__CORE__SQL_ALCHEMY_CONN`
2. Airflow 2.3.x with `AIRFLOW__CORE__SQL_ALCHEMY_CONN`
3. Airflow 2.3.x with`AIRFLOW__DATABASE__SQL_ALCHEMY_CONN

**Comment by nickhamlin** [comment]
Hi @DouweM , I'm happy to take a crack at that:

1.  This is the bottom of meltano.yml, which I think is all that's relevant here. This is the same for all 3 scenarios with the exception of the `pip_url`, which I've been editing then rebuilding the container to change airflow versions. 
```
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.3.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.3.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
```

2. Here's the relevant section of `docker_compose` that sets Airflow environment variables. This is also the same for all 3 situations.
```
x-airflow-env: &airflow-env
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://postgres:postgres@airflow-metadata-db/airflow
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
```

3. This is where it gets interesting. I went to run `meltano invoke --dump=config airflow` and I get the following error:

```
2022-07-07T00:04:42.456359Z [error    ] /project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)
Traceback (most recent call last):
  File "/project/.meltano/orchestrators/airflow/venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/__init__.py", line 35, in <module>
    from airflow import settings
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/settings.py", line 35, in <module>
    from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 1601, in <module>
    conf.validate()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 314, in validate
    self._validate_config_dependencies()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 408, in _validate_config_dependencies
    raise AirflowConfigException(f"error: cannot use sqlite with the {self.get('core', 'executor')}")
airflow.exceptions.AirflowConfigException: error: cannot use sqlite with the LocalExecutor

Command `airflow --help` failed
```

Interestingly, it doesn't appear that I'm able to run ANY commands involving airflow without getting this error. It also looks like anytime Airflow hits a weird error, it tries to be helpful and run `airflow --help` automatically, which is the origin of the last line in the error and happens even though I didn't run the help command myself. Example: I get the exact same error when running `meltano invoke airflow webserver`

All that said, I think I have another idea about what might be happening here. In pulling together the info above, I also realized I now have an `airflow--apache.lock` file, which is new. I believe this was created automatically when I reran `meltano add...` before posting my previous comment. Here's what it contains:

```
{
  "plugin_type": "orchestrators",
  "name": "airflow",
  "namespace": "airflow",
  "variant": "apache",
  "label": "Airflow",
  "docs": "https://docs.meltano.com/guide/orchestration",
  "repo": "https://github.com/apache/airflow",
  "pip_url": "apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt",
  "settings": [
    {
      "name": "core.dags_folder",
      "env": "AIRFLOW__CORE__DAGS_FOLDER",
      "value": "$MELTANO_PROJECT_ROOT/orchestrate/dags",
      "label": "DAGs Folder"
    },
    {
      "name": "core.plugins_folder",
      "env": "AIRFLOW__CORE__PLUGINS_FOLDER",
      "value": "$MELTANO_PROJECT_ROOT/orchestrate/plugins",
      "label": "Plugins Folder"
    },
    {
      "name": "core.sql_alchemy_conn",
      "env": "AIRFLOW__CORE__SQL_ALCHEMY_CONN",
      "value": "sqlite:///$MELTANO_PROJECT_ROOT/.meltano/orchestrators/airflow/airflow.db",
      "label": "SQL Alchemy Connection"
    },
    {
      "name": "core.load_examples",
      "env": "AIRFLOW__CORE__LOAD_EXAMPLES",
      "value": false,
      "label": "Load Examples"
    },
    {
      "name": "core.dags_are_paused_at_creation",
      "env": "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION",
      "value": false,
      "label": "Pause DAGs at Creation"
    },
    {
      "name": "webserver.web_server_port",
      "env": "AIRFLOW__WEBSERVER__WEB_SERVER_PORT",
      "value": 8080,
      "label": "Webserver Port"
    }
  ],
  "commands": {
    "create-admin": {
      "args": "users create --username admin --firstname FIRST_NAME --lastname LAST_NAME --role Admin --email admin@example.org",
      "description": "Create an admin user."
    },
    "ui": {
      "args": "webserver",
      "description": "Start the Airflow webserver."
    }
  },
  "requires": {
    "files": [
      {
        "name": "files-airflow",
        "variant": "meltano"
      }
    ]
  }
}
```

Among other things, this file is pretty clearly ALSO setting a value for `AIRFLOW__CORE__SQL_ALCHEMY_CONN` that uses the SQLite default path for airflow. Seeing this, I'm wondering if the values stored here aren't being overridden by the values stored in `docker-compose.yml`. This is where I plan to explore next. Thanks for your help and please let me know what other info might be helpful for me to provide!

**Comment by nickhamlin** [comment]
Well, it does look like the Airflow environment variables have the right values. When I run a command with `meltano --log-level=debug...` such that it spits out the values of all my env vars, I can spot the correct values showing up in the long list it comes back with:

```
'AIRFLOW__CORE__EXECUTOR': 'LocalExecutor',...[redacted]...., 'AIRFLOW__CORE__SQL_ALCHEMY_CONN': 'postgres://postgres:postgres@airflow-metadata-db/airflow'
```

**Comment by nickhamlin** [comment]
Here's the full error message for Option 3: Airflow 2.3.x withAIRFLOW__DATABASE__SQL_ALCHEMY_CONN

```
root@1cd9fee5388b:/project# meltano invoke --dump=config airflow
2022-07-07T00:58:07.209354Z [error    ] Traceback (most recent call last):
  File "/project/.meltano/orchestrators/airflow/venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/__init__.py", line 47, in <module>
    settings.initialize()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/settings.py", line 564, in initialize
    configure_orm()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/settings.py", line 270, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, connect_args=connect_args, **engine_args)
  File "<string>", line 2, in create_engine
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 339, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```

And here's Option 1: Airflow 2.1.x with AIRFLOW__CORE__SQL_ALCHEMY_CONN

```
root@65e3c89f7176:/project# meltano invoke --dump=config airflow
2022-07-07T01:08:57.223046Z [error    ] Traceback (most recent call last):
  File "/project/.meltano/orchestrators/airflow/venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/__init__.py", line 34, in <module>
    from airflow import settings
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/settings.py", line 34, in <module>
    from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 1113, in <module>
    conf.validate()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 201, in validate
    self._validate_config_dependencies()
  File "/project/.meltano/orchestrators/airflow/venv/lib/python3.9/site-packages/airflow/configuration.py", line 231, in _validate_config_dependencies
    raise AirflowConfigException(f"error: cannot use sqlite with the {self.get('core', 'executor')}")
airflow.exceptions.AirflowConfigException: error: cannot use sqlite with the LocalExecutor

Command `airflow --help` failed
```

**Comment by nickhamlin** [comment]
Making some progress that seems worth documenting. Sticking with Airflow 2.3.2, following the stack trace in the Option 3 error message above led me [here](https://github.com/apache/airflow/blob/01a5d8fe93a48883f4ae0d6ab65eeb82a30a09b9/airflow/configuration.py#L372), which gave me the idea to try updating the prefix of my connection string from `postgres` to `postgresql`, like this (new snippet from `docker-compose.yml`:

```
x-airflow-env: &airflow-env
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@airflow-metadata-db/airflow
  AIRFLOW__DATABASE__EXECUTOR: LocalExecutor
```
Using this allows airflow to actually start and the webserver and scheduler seem to stand up correctly again. This also opens up the chance to run actual airflow commands again, which is helpful because now I can do `meltano invoke airflow config get-value core executor` to check the executor that airflow thinks it's using. Interestingly, that command says it's still using the default `SequentialExecutor` for some reason, so more digging to do there.

**Comment by nickhamlin** [comment]
Thanks everyone! Circling back with a final recap from my end now that the dust has started to settle in hopes of leaving some clues for future searchers who might encounter the same issue.

We've got prod up and running again by following a version of @SBurwash 's recommendation and quickly migrating to Airflow 2.3.2. This process requires starting from a blank underlying airflow DB since migrating the old one doesn't seem to work. There wasn't really much value in retaining the old airflow data, so starting fresh worked fine (once I figured out the right environment variable names to use described in my comment above). 

One other gotcha to be aware of in this process is that Airflow 2 requires a manual CLI command to be run to initialize the first admin user.  Airflow 1.X didn't require this step before allowing access to the GUI, which threw me for a loop. Fortunately, it's straightforward to fix via a command like `meltano invoke airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin`. Once that runs, this user can then be used to log into the airflow GUI and additional users can be easily managed from there (including removing this temp admin user for clear security reasons). 

That's all the loose ends I can think of, but I'll come back and edit this comment if I come across others.

**Comment by tayloramurphy** [comment]
@nickhamlin thanks for the write-up! We do call out the new user creation in https://hub.meltano.com/orchestrators/airflow#next-steps and we have a command specified for it in the form of `meltano invoke airflow:create-admin` which basically [does what you say](https://github.com/meltano/hub/blob/main/_data/meltano/orchestrators/airflow/apache.yml#L15). Agreed though that the migration story isn't there yet.

**Comment by edgarrmondragon** [comment]
Maybe related: https://github.com/meltano/files-docker-compose/issues/6#event-7318518463
