### ISSUE TITLE
Uvicorn - Upgrade doesn't work

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6298]
Testing on Windows running with Uvicorn pressing the "Update" button doesn't work

**Comment by BuzzCutNorman** [comment]
This is the error I get when I just tried this on my Windows machine.  I installed meltano 2.03 in a venv and tried to upgrade to 2.1.0 using the `meltano ui` upgrade button.

```
Meltano UI is now available at http://localhost:5000
INFO:     127.0.0.1:51519 - "POST /api/v1/upgrade HTTP/1.1" 201 Created
2022-07-01T17:20:30.682684Z [error    ] exception calling callback for <Future at 0x1fcbc72b7c0 state=finished raised OSError> 
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "C:\development\.venv\meltano-old\lib\site-packages\flask_executor\executor.py", line 28, in propagate_exceptions_callback
    raise exc
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\development\.venv\meltano-old\lib\site-packages\flask_executor\executor.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "C:\development\.venv\meltano-old\lib\site-packages\flask\ctx.py", line 158, in wrapper
    return f(*args, **kwargs)
  File "C:\development\.venv\meltano-old\lib\site-packages\meltano\api\executor\__init__.py", line 55, in defer_upgrade
    MeltanoInvoker(project).invoke(
  File "C:\development\.venv\meltano-old\lib\site-packages\meltano\core\meltano_invoker.py", line 39, in invoke
    return subprocess.run(  # noqa: S603
  File "C:\Program Files\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by BuzzCutNorman** [comment]
The upgrade completes in the background at least in a new python virtual environment and newly initialized project.  Once the button is pushed and the upgrade is kicked off the UI seems to not detect that the upgrade has completed.

Here are the steps I used to test:
 ```
python -m venv .\.venv\meltano-previous
./.venv/meltano-previous/Scripts/Activate.ps1
pip install --upgrade pip
pip install meltano==2.0.3
 meltano init --no_usage_stats test-upgrade
cd  .\test-upgrade\
meltano --version
meltano --log-level debug ui
opened UI in a browser
clicked on "Update Available" button
clicked on the "Update Meltano" button
closed the browser
ctrl+c to stop meltano ui
meltano --version
```
Here is the console output when I ran these steps: 
[buzzcutnorman-meltano-ui-upgrade-20220701.log](https://github.com/meltano/meltano/files/9031653/buzzcutnorman-meltano-ui-upgrade-20220701.log)


I have noticed on Windows if the file(symbolic link) `.meltano/run/bin` is present in your project when you run the upgrade via `meltano upgrade` or the `melatno ui` "Upgrade Button" you will get the following WinError.

`[WinError 193] %1 is not a valid Win32 application`

if you remove the file and run `meltano upgrade` the upgrade will complete.  I am not sure what the long term ramification of deleting the file is.

**Comment by BuzzCutNorman** [comment]
I created a new issue #6467 for the `Win32 application` error and submitted a PR to fix the issue #6468 .

**Comment by visch** [comment]
Still need to dive into this a bit more, we should enable the upgrade test on Windows as well. https://github.com/meltano/meltano/blob/main/tests/meltano/cli/test_upgrade.py#L12 is probably the right test to be "reenabled for windows here!)

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI for Meltano 3.0
