### ISSUE TITLE
bug: `meltano install` exits success even if migrations fail

### ISSUE THREAD

**Issue by pdebelak** [meltano/meltano#6406]
I would expect `meltano install` to fail and exit with a non-zero exit code if the migrations fail. Instead, it proceeds to install plugins.

To reproduce:

```
$ meltano --version && python --version
meltano, version 2.2.0
Python 3.9.13
$ meltano init example
$ cd example
# this is just an example of a way to make migrations fail
$ sqlite3 .meltano/meltano.db "UPDATE alembic_version SET version_num = 'garbage';"
$ meltano install                                                                   
2022-07-12T16:35:37.771519Z [info     ] Environment 'dev' is active
2022-07-12T16:35:38.860146Z [error    ] No such revision or branch 'garbage' 
Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/meltano/core/migration_service.py", line 89, in upgrade
    self.ensure_migration_needed(script, context, head)
  File ".venv/lib/python3.9/site-packages/meltano/core/migration_service.py", line 55, in ensure_migration_needed
    for rev in script.iterate_revisions(current_head, "base"):
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 799, in iterate_revisions
    revisions, heads = fn(
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 1426, in _collect_upgrade_revisions
    for rev in self._parse_upgrade_target(
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 1218, in _parse_upgrade_target
    return self.get_revisions(target)
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 552, in get_revisions
    return tuple(
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 553, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File ".venv/lib/python3.9/site-packages/alembic/script/revision.py", line 624, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'garbage'
Cannot upgrade the system database. It might be corrupted or was created before database migrations where introduced (v0.34.0)
Installing 0 plugins...
$ echo $?                                                                           
0

**Comment by pdebelak** [comment]
This problem made it hard to realize that I was running into the problem from  #6405 since running `meltano install`  succeeded in our docker build but didn't actually successfully set up the database.
