### ISSUE TITLE
[Bug]: Freshly installed Meltano unusable due to werkzeug update

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6469]
### Meltano Version

2.3.0

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Any

### Description

On a freshly installed Meltano, any CLI command fails due to an import error in the `flask-login` dependency.

### Code

```python
$ meltano --version
Traceback (most recent call last):
  File "/opt/pipx_bin/meltano", line 5, in <module>
    from meltano.cli import main
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/meltano/cli/__init__.py", line 20, in <module>
    from . import (  # isort:skip # noqa: F401, WPS235
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/meltano/cli/user.py", line 5, in <module>
    from meltano.api.app import create_app
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/meltano/api/app.py", line 13, in <module>
    from meltano.api.security.auth import HTTP_READONLY_CODE
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/meltano/api/security/__init__.py", line 1, in <module>
    from flask_login import user_logged_in
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/flask_login/login_manager.py", line 35, in <module>
    from .utils import _create_identifier
  File "/opt/pipx/venvs/meltano/lib/python3.8/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/opt/pipx/venvs/meltano/lib/python3.8/site-packages/werkzeug/routing/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by edgarrmondragon** [comment]
Related:

- https://github.com/maxcountryman/flask-login/issues/686

**Comment by edgarrmondragon** [comment]
One temporary solution is to pin `werkzeug` to `<=2.1.3` and release a patch version of Meltano, while the `flask-login` issue is sorted out.

**Comment by edgarrmondragon** [comment]
Seen in GitLab CI too: https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2762541540

**Comment by davidism** [comment]
Flask-Login 0.6.2 was released.

**Comment by edgarrmondragon** [comment]
> Flask-Login 0.6.2 was released.

awesome, thank you so much @davidism!
