### ISSUE TITLE
bug: Fresh Install via PIP showing warnings 

### ISSUE THREAD

**Issue by EMCP** [meltano/meltano#6624]
### Meltano Version

2.4.0

### Python Version

3.8.10

### Bug scope

Other

### Operating System

Ubuntu 22.04 (LXD)

### Description

I am running within an LXD container, attempting to just install Meltano.. with no pinning or help by myself other than getting the latest PIP

```
ubuntu@juju-45fbf0-22:~$ pip3 install meltano poetry                                                                                                                                         
Collecting meltano                                                                                                                                                                           
  Downloading meltano-2.4.0-py3-none-any.whl (3.8 MB)                                                                                                                                        
     |████████████████████████████████| 3.8 MB 11.2 MB/s                                                                                                                                     
Collecting poetry                                                                                                                                                                            
  Downloading poetry-1.1.14-py2.py3-none-any.whl (175 kB)                                                                                                                                    
     |████████████████████████████████| 175 kB 11.0 MB/s                                                                                                                                     
Collecting backoff<3.0.0,>=2.1.2                                                                                                                                                             
  Downloading backoff-2.1.2-py3-none-any.whl (14 kB)            
      ....
Successfully built atomicwrites click-default-group meltano-flask-security Flask-Mail Flask-Principal speaklater                                                                             
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.                                                                                                                  
ERROR: flask 2.2.2 has requirement Werkzeug>=2.2.2, but you'll have werkzeug 2.1.2 which is incompatible.                                                                                    
ERROR: importlib-resources 5.9.0 has requirement zipp>=3.1.0; python_version < "3.10", but you'll have zipp 1.0.0 which is incompatible.                                                     
ERROR: poetry 1.1.14 has requirement packaging<21.0,>=20.4, but you'll have packaging 21.3 which is incompatible. 
```

and then any meltano commands basically don't work

```
$ .local/bin/meltano 
Traceback (most recent call last):
  File ".local/bin/meltano", line 5, in <module>
    from meltano.cli import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/meltano/cli/__init__.py", line 20, in <module>
    from . import (  # isort:skip # noqa: F401, WPS235
  File "/home/ubuntu/.local/lib/python3.8/site-packages/meltano/cli/user.py", line 7, in <module>
    from meltano.api.app import create_app
  File "/home/ubuntu/.local/lib/python3.8/site-packages/meltano/api/app.py", line 8, in <module>
    from flask import Flask, g, jsonify, request  # noqa: WPS347
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

```

### Code

```python
These are running as root


apt -y install python3-dev python3-pip libpq-dev python3-venv python-is-python3
pip3 install --upgrade pip

sudo -u ubuntu pip3 install --upgrade pip
sudo -u ubuntu pip3 install meltano poetry
```
```

**Comment by EMCP** [comment]
I *think* most of my problems go away when I prepend this

```
sudo -u ubuntu pip3 install zipp==3.1.0 --no-warn-script-location
```

**Comment by tayloramurphy** [comment]
@meltano/engineering any suggestions or paths forward here?

**Comment by edgarrmondragon** [comment]
@EMCP @tayloramurphy Dependency resolution is weird 🤔. I don't know why your installation of `pip` is getting all those incompatible versions without trying older versions, and for example  resolving to Flask `2.1.3` since that's the latest compatible with Werkzeug `<2.2`.

Installing fresh with `pipx`:

```console
$ pipx install meltano --suffix="@test"
$ pipx runpip meltano@test list
Package                Version
---------------------- -----------
aiodocker              0.21.0
aiohttp                3.8.1
aiosignal              1.2.0
alembic                1.8.1
aniso8601              9.0.1
anyio                  3.6.1
asgiref                3.5.2
async-timeout          4.0.2
atomicwrites           1.4.1
attrs                  22.1.0
Authlib                1.0.1
Babel                  2.10.3
backoff                2.1.2
bcrypt                 3.2.2
blinker                1.5
cached-property        1.5.2
certifi                2022.6.15
cffi                   1.15.1
charset-normalizer     2.1.0
click                  8.1.3
click-default-group    1.2.2
cryptography           37.0.4
dnspython              2.2.1
email-validator        1.2.1
fasteners              0.17.3
Flask                  2.1.3
Flask-BabelEx          0.9.4
Flask-Cors             3.0.10
Flask-Executor         0.10.0
Flask-Login            0.6.1
Flask-Mail             0.9.1
Flask-Principal        0.4.0
Flask-RESTful          0.3.9
Flask-SQLAlchemy       2.5.1
Flask-WTF              1.0.1
flatten-dict           0.4.2
frozenlist             1.3.1
greenlet               1.1.2
gunicorn               20.1.0
h11                    0.13.0
httptools              0.4.0
idna                   3.3
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.13.0
Mako                   1.2.1
Markdown               3.4.1
MarkupSafe             2.1.1
meltano                2.4.0
meltano-flask-security 0.1.0
multidict              6.0.2
packaging              21.3
passlib                1.7.4
pip                    22.2.2
psutil                 5.9.1
psycopg2-binary        2.9.3
pycparser              2.21
pyhumps                3.7.2
pyparsing              3.0.9
pyrsistent             0.18.1
python-dotenv          0.20.0
python-gitlab          3.8.1
pytz                   2022.2.1
pytz-deprecation-shim  0.1.0.post0
PyYAML                 5.4.1
requests               2.28.1
requests-toolbelt      0.9.1
ruamel.yaml            0.17.21
ruamel.yaml.clib       0.2.6
setuptools             65.0.2
six                    1.16.0
smtpapi                0.4.12
sniffio                1.2.0
snowplow-tracker       0.10.0
speaklater             1.3
SQLAlchemy             1.4.40
structlog              21.5.0
typing_extensions      4.3.0
tzdata                 2022.2
tzlocal                4.2
urllib3                1.26.11
uvicorn                0.17.6
uvloop                 0.16.0
watchgod               0.8.2
websockets             10.3
Werkzeug               2.1.2
wheel                  0.37.1
WTForms                3.0.1
yarl                   1.8.1
```

We could still prevent this buggy resolution by

- requiring Flask `<2.2` to ensure compatibility with our older Werkzeug or
- bump both the minimum for both dependencies

The latter is preferable IMO. I'll start a PR since that's a quick fix.

**Comment by EMCP** [comment]
I can confirm I have the latest meltano installing just fine via pipx `v2.17.1` just this morning.. thanks for following up
