### ISSUE TITLE
bug: Hard to debug valid JSON contents in generated catalog file

### ISSUE THREAD

**Issue by alanmcruickshank** [meltano/meltano#6878]
### Meltano Version

1.79.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Python Docker image

### Description

Following an upgrade from 1.76.0 to 1.79.0 I get the following error when trying to run once of our pipelines:
```
[2022-10-12 22:20:20,005] {pod_launcher.py:176} INFO - Event: tap-yodel-cat-target-snowflake.26bf63e794b442c7b35a66827cb0c95a had an event of type Running
[2022-10-12 22:20:20,018] {pod_launcher.py:136} INFO - meltano                       | Running extract & load...
[2022-10-12 22:20:20,018] {pod_launcher.py:136} INFO - meltano                       | Found state from 2022-10-12 20:00:11.154879.
[2022-10-12 22:20:21,612] {pod_launcher.py:136} INFO - meltano                       | ELT could not be completed: Cannot start extractor: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)
```

No further error is given. Not sure how to move past this or resolve the problem. I'm going to try upgrading to an even later version to try and solve the problem.

**Comment by alanmcruickshank** [comment]
Update on diagnosis:
- it's tap specific (others aren't affected).
- issue persists, but with slightly better logging on `1.105.0`.

Logs from running `1.105.0`:
```
[2022-10-12 22:59:08,330] {pod_launcher.py:113} WARNING - Pod not yet started: tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07
[2022-10-12 22:59:09,338] {pod_launcher.py:176} INFO - Event: tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 had an event of type Running
[2022-10-12 22:59:09,348] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.003108Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mjob_id[0m=[35mtap-yodel-cat-target-snowflake[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1cc70823-e2b6-43f9-85ac-fde7cc4f0214[0m
[2022-10-12 22:59:09,349] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.113424Z[0m [[32m[1minfo     [0m] [1mFound state from 2022-10-12 20:00:11.154879.[0m
[2022-10-12 22:59:09,804] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.803565Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Cannot start extractor: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0).[0m [36mcmd_type[0m=[35melt[0m [36mjob_id[0m=[35mtap-yodel-cat-target-snowflake[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1cc70823-e2b6-43f9-85ac-fde7cc4f0214[0m [36mstdio[0m=[35mstderr[0m
[2022-10-12 22:59:09,804] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.803852Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mjob_id[0m=[35mtap-yodel-cat-target-snowflake[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1cc70823-e2b6-43f9-85ac-fde7cc4f0214[0m [36mstdio[0m=[35mstderr[0m
[2022-10-12 22:59:09,804] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.803971Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/code/.meltano/logs/elt/tap-yodel-cat-target-snowflake/1cc70823-e2b6-43f9-85ac-fde7cc4f0214/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mjob_id[0m=[35mtap-yodel-cat-target-snowflake[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1cc70823-e2b6-43f9-85ac-fde7cc4f0214[0m [36mstdio[0m=[35mstderr[0m
[2022-10-12 22:59:09,804] {pod_launcher.py:136} INFO - [2m2022-10-12T22:59:09.804076Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mjob_id[0m=[35mtap-yodel-cat-target-snowflake[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1cc70823-e2b6-43f9-85ac-fde7cc4f0214[0m [36mstdio[0m=[35mstderr[0m
[2022-10-12 22:59:09,816] {pod_launcher.py:136} INFO - ELT could not be completed: Cannot start extractor: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0).
[2022-10-12 22:59:09,816] {pod_launcher.py:136} INFO - For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
[2022-10-12 22:59:09,817] {pod_launcher.py:136} INFO - Note that you can also check the generated log file at '/code/.meltano/logs/elt/tap-yodel-cat-target-snowflake/1cc70823-e2b6-43f9-85ac-fde7cc4f0214/elt.log'.
[2022-10-12 22:59:09,817] {pod_launcher.py:136} INFO - For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2022-10-12 22:59:25,858] {pod_launcher.py:176} INFO - Event: tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 had an event of type Running
[2022-10-12 22:59:25,858] {pod_launcher.py:155} INFO - Pod tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 has state running
[2022-10-12 22:59:27,866] {pod_launcher.py:176} INFO - Event: tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 had an event of type Failed
[2022-10-12 22:59:27,866] {pod_launcher.py:286} ERROR - Event with job id tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 Failed
[2022-10-12 22:59:27,872] {pod_launcher.py:176} INFO - Event: tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 had an event of type Failed
[2022-10-12 22:59:27,872] {pod_launcher.py:286} ERROR - Event with job id tap-yodel-cat-target-snowflake.66f258c7de2e4e01be0d501294217b07 Failed
```

It appears that the catalog it's finding is somehow corrupt.

**Comment by alanmcruickshank** [comment]
I've managed to recreate the issue locally too - so I suspect something about the configuration of the tap and the configuration of meltano. Can anyone advise on how to see what catalog the tap is generating for debugging?

**Comment by edgarrmondragon** [comment]
@alanmcruickshank you could try inspecting the output of `meltano invoke --dump=config <your tap>` to see if it's a valid catalog.

This JSON error (which could be handled better tbf) suggests the catalog file is empty:

```
Expecting value: line 1 column 1 (char 0).
```

**Comment by alanmcruickshank** [comment]
Thanks @edgarrmondragon - I assume you meant `--dump=catalog` as `--dump=config` is working fine. In any case I get the slightly unhelpful error message:
```
$ pipenv run meltano invoke --dump=catalog tap-yodel
Loading .env environment variables...
Could not dump catalog: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)
```

I assume your judgement is right that the catalog is empty, however I'm confused: If I invoke the tap directly `pipenv tap-yodel --discover --config config.json` I get a valid JSON output, also comparing the structure of the tap to sample taps like the (powerbi one)[https://github.com/dataops-tk/tap-powerbi-metadata] everything looks the same.

**Comment by DouweM** [comment]
@alanmcruickshank Can you try running with `meltano --log-level=debug ...` so we get some additional details?

**Comment by alanmcruickshank** [comment]
Running with debug logging gets this (I've edited out some of the details for security with a ...):

```
> pipenv run meltano --log-level=debug invoke tap-yodel
Loading .env environment variables...
2022-10-14T12:32:15.098679Z [debug    ] Creating engine <meltano.core.project.Project object at 0x000001EBBE593A60>@postgresql://...:5432
2022-10-14T12:32:17.009859Z [debug    ] Using proactor: IocpProactor
2022-10-14T12:32:17.474034Z [debug    ] Created configuration at C:\Users\alanc\dev\tails-data-meltano\meltano\.meltano\run\tap-yodel\tap.3c21d13d-81a8-42e8-a690-6776beb3e578.config.json
2022-10-14T12:32:17.478986Z [debug    ] Could not find tap.properties.json in C:\Users\alanc\dev\tails-data-meltano\meltano\.meltano\extractors\tap-yodel\tap.properties.json, skipping.
2022-10-14T12:32:17.486358Z [debug    ] Could not find tap.properties.cache_key in C:\Users\alanc\dev\tails-data-meltano\meltano\.meltano\extractors\tap-yodel\tap.properties.cache_key, skipping.
2022-10-14T12:32:17.490355Z [debug    ] Could not find state.json in C:\Users\alanc\dev\tails-data-meltano\meltano\.meltano\extractors\tap-yodel\state.json, skipping.
2022-10-14T12:32:17.500381Z [debug    ] Invoking: ['C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano\\.meltano\\extractors\\tap-yodel\\venv\\Scripts\\tap-yodel', '--config', 'C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano\\.meltano\\run\\tap-yodel\\tap.3c21d13d-81a8-42e8-a690-6776beb3e578.config.json', '--discover']
2022-10-14T12:32:17.505372Z [debug    ] Env: {'MELTANO_DATABASE_URI': 'postgresql://...:5432', ..., 'USERNAME': 'alanc', 'USERPROFILE': 'C:\\Users\\alanc', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', 'PIP_DISABLE_PIP_VERSION_CHECK': '1', 'PIP_PYTHON_PATH': 'C:\\Python39\\python.exe', 'PYTHONDONTWRITEBYTECODE': '1', 'PIPENV_ACTIVE': '1', 'MELTANO_JOB_TRIGGER': 'cli', 'MELTANO_PROJECT_ROOT': 'C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano', 'MELTANO_ENVIRONMENT': '', 'MELTANO_SEND_ANONYMOUS_USAGE_STATS': 'true', 'MELTANO_PROJECT_ID': '455a5b27-ff3c-4a15-8674-097600d97aa5', 'MELTANO_DATABASE_MAX_RETRIES': '3', 'MELTANO_DATABASE_RETRY_TIMEOUT': '5', 'MELTANO_PROJECT_READONLY': 'false', 'MELTANO_DISCOVERY_URL': 'https://discovery.meltano.com/discovery.yml', 'MELTANO_ELT_BUFFER_SIZE': '10485760', 'MELTANO_CLI_LOG_LEVEL': 'debug', 'MELTANO_CLI_LOG_CONFIG': 'logging.yaml', 'MELTANO_UI_BIND_HOST': '0.0.0.0', 'MELTANO_API_HOSTNAME': '0.0.0.0', 'MELTANO_UI_BIND_PORT': '5000', 'MELTANO_API_PORT': '5000', 'PORT': '5000', 'MELTANO_UI_SESSION_COOKIE_SECURE': 'false', 'MELTANO_UI_SECRET_KEY': '...', 'MELTANO_UI_PASSWORD_SALT': '...', 'MELTANO_UI_WORKERS': '4', 'WORKERS': '4', 'WEB_CONCURRENCY': '4', 'MELTANO_UI_FORWARDED_ALLOW_IPS': '127.0.0.1', 'FORWARDED_ALLOW_IPS': '127.0.0.1', 'MELTANO_UI_READONLY': 'false', 'MELTANO_READONLY': 'false', 'MELTANO_UI_AUTHENTICATION': 'false', 'MELTANO_AUTHENTICATION': 'false', 'MELTANO_UI_ANONYMOUS_READONLY': 'false', 'MELTANO_UI_NOTIFICATION': 'false', 'MELTANO_NOTIFICATION': 'false', 'MELTANO_UI_ANALYSIS': 'false', 'MAIL_SERVER': 'localhost', 'MELTANO_MAIL_SERVER': 'localhost', 'MAIL_PORT': '1025', 'MELTANO_MAIL_PORT': '1025', 'MAIL_DEFAULT_SENDER': '"Meltano" <bot@meltano.com>', 'MELTANO_MAIL_DEFAULT_SENDER': '"Meltano" <bot@meltano.com>', 'MAIL_USE_TLS': 'false', 'MELTANO_MAIL_USE_TLS': 'false', 'MAIL_DEBUG': 'false', 'MELTANO_MAIL_DEBUG': 'false', 'MAIL_SENDGRID_UNSUBSCRIBE_GROUP_ID': '...', 'MELTANO_MAIL_SENDGRID_UNSUBSCRIBE_GROUP_ID': '...', 'MELTANO_OAUTH_SERVICE_PROVIDERS': 'all', 'MELTANO_TRACKING_IDS_CLI': 'UA-132758957-3', 'MELTANO_CLI_TRACKING_ID': 'UA-132758957-3', 'MELTANO_TRACKING_IDS_UI': 'UA-132758957-2', 'MELTANO_UI_TRACKING_ID': 'UA-132758957-2', 'MELTANO_TRACKING_IDS_UI_EMBED': 'UA-132758957-6', 'MELTANO_EMBED_TRACKING_ID': 'UA-132758957-6', 'MELTANO_SNOWPLOW_COLLECTOR_ENDPOINTS': '["https://sp.meltano.com"]', 'MELTANO_FF_LOCK_FILES': 'false', 'MELTANO_EXPERIMENTAL': 'false', 'MELTANO_EXTRACTOR_NAME': 'tap-yodel', 'MELTANO_EXTRACTOR_NAMESPACE': 'tap_yodel', 'MELTANO_EXTRACTOR_VARIANT': 'original', 'TAP_YODEL_HOST': '...', 'MELTANO_EXTRACT_HOST': '...', 'TAP_YODEL__LOAD_SCHEMA': 'tap_yodel', 'MELTANO_EXTRACT__LOAD_SCHEMA': 'tap_yodel', 'TAP_YODEL__SELECT': '["*.*"]', 'MELTANO_EXTRACT__SELECT': '["*.*"]', 'TAP_YODEL__METADATA': '{}', 'MELTANO_EXTRACT__METADATA': '{}', 'TAP_YODEL__SCHEMA': '{}', 'MELTANO_EXTRACT__SCHEMA': '{}', 'TAP_YODEL__SELECT_FILTER': '[]', 'MELTANO_EXTRACT__SELECT_FILTER': '[]', 'VIRTUAL_ENV': 'C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano\\.meltano\\extractors\\tap-yodel\\venv'}
2022-10-14T12:32:21.551675Z [debug    ] Deleted configuration at C:\Users\alanc\dev\tails-data-meltano\meltano\.meltano\run\tap-yodel\tap.3c21d13d-81a8-42e8-a690-6776beb3e578.config.json
2022-10-14T12:32:21.627437Z [debug    ] Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\plugin\singer\tap.py", line 369, in discover_catalog
    catalog = json.load(catalog_file)
  File "C:\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\__init__.py", line 51, in main
    cli(obj={"project": None})
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\params.py", line 23, in decorate

    return func(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\params.py", line 56, in decorate

    func(project, *args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\invoke.py", line 88, in invoke
    exit_code = run_async(
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\utils\__init__.py", line 50, in run_async
    loop.run_until_complete(future)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\invoke.py", line 131, in _invoke

    handle = await invoker.invoke_async(*plugin_args, command=command_name)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\plugin_invoker.py", line 388, in invoke_async
    async with self._invoke(*args, **kwargs) as (
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\plugin_invoker.py", line 364, in _invoke
    async with self.plugin.trigger_hooks("invoke", self, args):
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\behavior\hookable.py", line 87, in trigger_hooks
    await self.__class__.trigger(self, f"before_{hook_name}", *args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\behavior\hookable.py", line 115, in trigger
    raise err
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\behavior\hookable.py", line 107, in trigger
    await hook_func(target, *args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\plugin\singer\tap.py", line 313, in discover_catalog_hook
    await self.discover_catalog(plugin_invoker)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\core\plugin\singer\tap.py", line 373, in discover_catalog
    raise PluginExecutionError(
meltano.core.plugin.error.PluginExecutionError: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\meltano\cli\__init__.py", line 59, in main
    raise CliError(str(err)) from err
meltano.cli.utils.CliError: Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)
Catalog discovery failed: invalid catalog: Expecting value: line 1 column 1 (char 0)
```

Are these logs any help?

**Comment by edgarrmondragon** [comment]
> Is this instead about an issue loading the _existing catalog_?

@alanmcruickshank  Doesn't look like. This line in the debug output suggests it's generating the catalog:

```
Invoking: ['C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano\\.meltano\\extractors\\tap-yodel\\venv\\Scripts\\tap-yodel', '--config', 'C:\\Users\\alanc\\dev\\tails-data-meltano\\meltano\\.meltano\\run\\tap-yodel\\tap.3c21d13d-81a8-42e8-a690-6776beb3e578.config.json', '--discover']
```

This make me think that the generated config is not right, and the tap depends on config to generate the catalog?

How would the output of `--discover` look like when using the config generated by Meltano:

```
pipenv run meltano invoke --dump=config tap-yodel > config.json
pipenv run tap-yodel --config config.json --discover
```

**Comment by alanmcruickshank** [comment]
If I run those commands. The first runs fine:

```
> pipenv run meltano invoke --dump=config tap-yodel > config.json
Loading .env environment variables...
```
And produces the following config (I've removed the value for security, but it looks fine):
```json
{
  "host": "..."
}
```

The second command fails, and has the following trace:
```
> pipenv run tap-yodel --config config.json --discover
Loading .env environment variables...
INFO - 2022-10-17 09:39:47,560 - tap-yodel - tap-yodel v0.2.0, Meltano SDK v0.11.1
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\Scripts\tap-yodel.EXE\__main__.py", line 7, in <module>
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\singer_sdk\tap_base.py", line 489, in cli
    tap = cls(  # type: ignore  # Ignore 'type not callable'
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\singer_sdk\tap_base.py", line 68, in __init__
    super().__init__(
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\singer_sdk\plugin_base.py", line 106, in __init__
    config_dict.update(read_json_file(config_path))
  File "C:\Users\alanc\.virtualenvs\meltano-9aGVMBGe\lib\site-packages\singer_sdk\helpers\_util.py", line 22, in read_json_file
    return cast(dict, json.loads(Path(path).read_text()))
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

...which looks like it's having trouble reading the config file we've just passed it.

On the plus side, I think we've concluded that this isn't a `meltano` issue! On the downside, it looks like the issue is somewhere between the tap and the `singer-sdk`.

**Comment by alanmcruickshank** [comment]
Oh man - I've found the issue 🤦 .

The config file from `pipenv run meltano invoke --dump=config tap-yodel > config.json` is being exported in `utf16`!?

If I resave the config.json file in `utf8` then it all works fine.

**Comment by alanmcruickshank** [comment]
Nope - even stupider error.

The tap was outputting it's logs to `stdout` rather than `stderr`.

If I add some additional logging to inspect the loaded config file directly before reading to json, the content begins with: `2022-10-17T09:22:40.747863Z [debug    ] Loading catalog content: 'INFO - 2022-10-17 10:22:40,598 - tap-yodel - tap-yodel v0.2.0, Meltano SDK v0.11.1\nINFO - 2022-10-17...`

I think we can say that this issue is solved - but this was really really hard to debug. At the very least would it be sensible to output a sample of the loaded config files if they fail to load (which would have identified this issue immediately), or better - validate the json on save rather than on load so that it's easier to better catch this at source?

**Comment by edgarrmondragon** [comment]
> The tap was outputting it's logs to `stdout` rather than `stderr`.

@alanmcruickshank ah that makes sense!

> I think we can say that this issue is solved - but this was really really hard to debug. At the very least would it be sensible to output a sample of the loaded config files if they fail to load (which would have identified this issue immediately), or better - validate the json on save rather than on load so that it's easier to better catch this at source?

I agree. I see you're using the Singer SDK so it should be fairly easy to add both

1) a better error message when trying to load an invalid JSON file https://github.com/meltano/sdk/issues/1081
2) add testing helpers so users can ensure the output of `--discover` is valid JSON https://github.com/meltano/sdk/issues/1082
