### ISSUE TITLE
bug: unable to install latest meltano version with Python 3.11

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#7220]
### Meltano Version

9b8455447be6aedcbfd8b09b904c7ba847774cff

### Python Version

3.11

### Bug scope

API

### Operating System

macOS Monterey

### Description

I saw that https://github.com/meltano/meltano/pull/7210 was merged today so I wanted to try upgrading to Python 3.11 my project. 

I ran `pyenv install 3.11.1` and `pyenv local 3.11.1` to set the Python version and then ran this command to try installing meltano

```shell
pip install 'meltano @ git+https://github.com/meltano/meltano@9b8455447be6aedcbfd8b09b904c7ba847774cff'
```

(`python -m pip` vs `pip` here has the same effect).

### Code

```
Full error log from `python -m pip install 'meltano @ git+https://github.com/meltano/meltano@9b8455447be6aedcbfd8b09b904c7ba847774cff'` command:


Collecting meltano@ git+https://github.com/meltano/meltano@9b8455447be6aedcbfd8b09b904c7ba847774cff
  Cloning https://github.com/meltano/meltano (to revision 9b8455447be6aedcbfd8b09b904c7ba847774cff) to /private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-gwn8in6c/meltano_f7db06b8032046339bd2f7f0b7c73327
  Resolved https://github.com/meltano/meltano to commit 9b8455447be6aedcbfd8b09b904c7ba847774cff
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting aiodocker<0.22.0,>=0.21.0
  Using cached aiodocker-0.21.0-py3-none-any.whl (34 kB)
Collecting aiohttp<4.0.0,>=3.4.4
  Using cached aiohttp-3.8.3-cp311-cp311-macosx_10_9_x86_64.whl (355 kB)
Collecting alembic<2.0.0,>=1.5.0
  Using cached alembic-1.9.2-py3-none-any.whl (210 kB)
Collecting atomicwrites<2.0.0,>=1.2.1
  Using cached atomicwrites-1.4.1.tar.gz (14 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting authlib<2.0.0,>=1.0.1
  Using cached Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
Collecting backoff<3.0.0,>=2.1.2
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting bcrypt<4.0.0,>=3.2.0
  Using cached bcrypt-3.2.2-cp36-abi3-macosx_10_10_universal2.whl (50 kB)
Collecting cached-property<2,>=1
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting click<9.0,>=8.1
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting click-default-group<2.0.0,>=1.2.1
  Using cached click-default-group-1.2.2.tar.gz (3.3 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting croniter<2.0.0,>=1.3.5
  Using cached croniter-1.3.8-py2.py3-none-any.whl (18 kB)
Collecting email-validator<2.0.0,>=1.1.2
  Using cached email_validator-1.3.1-py2.py3-none-any.whl (22 kB)
Collecting fasteners<0.18.0,>=0.17.3
  Using cached fasteners-0.17.3-py3-none-any.whl (18 kB)
Collecting flask<3.0,>=2.1
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Collecting flask-cors<4.0.0,>=3.0.7
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting flask-executor<0.11,>=0.10
  Using cached Flask_Executor-0.10.0-py3-none-any.whl (9.3 kB)
Collecting flask-login==0.6.1
  Using cached Flask_Login-0.6.1-py3-none-any.whl (17 kB)
Collecting flask-restful<0.4.0,>=0.3.7
  Using cached Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)
Collecting flask-sqlalchemy<3.0.0,>=2.4.4
  Using cached Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting flatten-dict<1,>=0
  Using cached flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Collecting gunicorn<21.0.0,>=20.1.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting jsonschema<5.0,>=4.9
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting meltano-flask-security<0.2.0,>=0.1.0
  Using cached meltano-flask-security-0.1.0.tar.gz (116 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting packaging<22.0,>=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting psutil<6.0.0,>=5.6.3
  Using cached psutil-5.9.4-cp36-abi3-macosx_10_9_x86_64.whl (243 kB)
Collecting psycopg2-binary<3.0.0,>=2.8.5
  Using cached psycopg2_binary-2.9.5-cp311-cp311-macosx_10_9_universal2.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.3 MB)
Collecting pyhumps<4.0.0,>=3.0.0
  Using cached pyhumps-3.8.0-py3-none-any.whl (6.1 kB)
Collecting python-dotenv<0.21.0,>=0.20.0
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting python-gitlab<4.0.0,>=3.5.0
  Using cached python_gitlab-3.12.0-py3-none-any.whl (130 kB)
Collecting pyyaml<7.0.0,>=6.0.0
  Using cached PyYAML-6.0-cp311-cp311-macosx_10_9_x86_64.whl (188 kB)
Collecting requests<3.0.0,>=2.23.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting rich<13.0.0,>=12.5.1
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting ruamel.yaml<0.18.0,>=0.17.21
  Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
Collecting smart-open<7.0.0,>=6.2.0
  Using cached smart_open-6.3.0-py3-none-any.whl (56 kB)
Collecting smtpapi<0.5.0,>=0.4.1
  Using cached smtpapi-0.4.12-py3-none-any.whl (4.7 kB)
Collecting snowplow-tracker<0.11.0,>=0.10.0
  Using cached snowplow_tracker-0.10.0-py3-none-any.whl (28 kB)
Collecting sqlalchemy<2.0.0,>=1.3.19
  Using cached SQLAlchemy-1.4.46-cp311-cp311-macosx_10_9_universal2.whl (1.6 MB)
Collecting structlog<22.0.0,>=21.2.0
  Using cached structlog-21.5.0-py3-none-any.whl (53 kB)
Collecting tzlocal<5.0.0,>=4.2.0
  Using cached tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting uvicorn[standard]<0.18.0,>=0.17.6
  Using cached uvicorn-0.17.6-py3-none-any.whl (53 kB)
Collecting virtualenv<21.0.0,>=20.17.1
  Using cached virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
Collecting werkzeug<=2.1.3,>=2.1
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting attrs>=17.3.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp311-cp311-macosx_10_9_x86_64.whl (29 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.8.2-cp311-cp311-macosx_10_9_x86_64.whl (59 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp311-cp311-macosx_10_9_x86_64.whl (35 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting Mako
  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)
Collecting cryptography>=3.2
  Using cached cryptography-39.0.0-cp36-abi3-macosx_10_12_x86_64.whl (2.9 MB)
Collecting cffi>=1.1
  Using cached cffi-1.15.1-cp311-cp311-macosx_10_9_x86_64.whl (179 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Collecting idna>=2.0.0
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting flask<3.0,>=2.1
  Using cached Flask-2.2.1-py3-none-any.whl (101 kB)
  Using cached Flask-2.2.0-py3-none-any.whl (101 kB)
  Using cached Flask-2.1.3-py3-none-any.whl (95 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting aniso8601>=0.82
  Using cached aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
Collecting pytz
  Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
Requirement already satisfied: setuptools>=3.0 in /Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages (from gunicorn<21.0.0,>=20.1.0->meltano@ git+https://github.com/meltano/meltano@9b8455447be6aedcbfd8b09b904c7ba847774cff) (65.5.0)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp311-cp311-macosx_10_9_universal2.whl (82 kB)
Collecting Flask-Mail>=0.7.3
  Using cached Flask-Mail-0.9.1.tar.gz (45 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Flask-Principal>=0.3.3
  Using cached Flask-Principal-0.4.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Flask-WTF>=0.13.1
  Using cached Flask_WTF-1.1.1-py3-none-any.whl (12 kB)
Collecting Flask-BabelEx>=0.9.3
  Using cached Flask_BabelEx-0.9.4-py3-none-any.whl (8.7 kB)
Collecting passlib>=1.7
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting requests-toolbelt>=0.9.1
  Using cached requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Collecting greenlet!=0.4.17
  Using cached greenlet-2.0.1-cp311-cp311-macosx_10_9_universal2.whl (259 kB)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting asgiref>=3.4.0
  Using cached asgiref-3.6.0-py3-none-any.whl (23 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting websockets>=10.0
  Using cached websockets-10.4-cp311-cp311-macosx_10_9_x86_64.whl (97 kB)
Collecting httptools>=0.4.0
  Using cached httptools-0.5.0-cp311-cp311-macosx_10_9_x86_64.whl (157 kB)
Collecting watchgod>=0.6
  Using cached watchgod-0.8.2-py3-none-any.whl (12 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0
  Using cached uvloop-0.17.0-cp311-cp311-macosx_10_9_x86_64.whl (1.5 MB)
Collecting distlib<1,>=0.3.6
  Using cached distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Collecting filelock<4,>=3.4.1
  Using cached filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting platformdirs<3,>=2.4
  Using cached platformdirs-2.6.2-py3-none-any.whl (14 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting Babel>=1.0
  Using cached Babel-2.11.0-py3-none-any.whl (9.5 MB)
Collecting speaklater>=1.2
  Using cached speaklater-1.3.tar.gz (3.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting blinker
  Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting WTForms
  Using cached WTForms-3.0.1-py3-none-any.whl (136 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp311-cp311-macosx_10_9_x86_64.whl (13 kB)
Collecting anyio<4,>=3.0.0
  Using cached anyio-3.6.2-py3-none-any.whl (80 kB)
Collecting tzdata
  Using cached tzdata-2022.7-py2.py3-none-any.whl (340 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Building wheels for collected packages: meltano
  Building wheel for meltano (pyproject.toml): started
  Building wheel for meltano (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for meltano (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      0.21.3
      yarn install v0.21.3
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      error An unexpected error occurred: "EACCES: permission denied, unlink '/Users/matt/Library/Caches/Yarn/npm-v-calendar-1.1.1-8e77be97013deea0eb2b09b381cdd856f7a64b23/.yarn-tarball.tgz'".
      info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-gwn8in6c/meltano_f7db06b8032046339bd2f7f0b7c73327/src/webapp/yarn-error.log".
      info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
      yarn build v0.21.3
      $ vue-cli-service build
      sh: vue-cli-service: command not found
      error Command failed with exit code 127.
      Traceback (most recent call last):
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-build-env-3c8d0hm5/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-build-env-3c8d0hm5/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-gwn8in6c/meltano_f7db06b8032046339bd2f7f0b7c73327/scripts/build.py", line 93, in custom_build_wheel
          include_webapp()
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-gwn8in6c/meltano_f7db06b8032046339bd2f7f0b7c73327/scripts/build.py", line 52, in include_webapp
          shutil.copy(
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/shutil.py", line 419, in copy
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/shutil.py", line 256, in copyfile
          with open(src, 'rb') as fsrc:
               ^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'src/webapp/dist/index.html'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for meltano
Failed to build meltano
ERROR: Could not build wheels for meltano, which is required to install pyproject.toml-based projects
```

**Comment by menzenski** [comment]
Turns out the issue was that I did not have yarn installed.

With Node 16 and yarn installed, I was able to successfully install meltano this way!

**Comment by WillDaSilva** [comment]
Replicated in a `python:3.11` Docker container.

Resolved on Slack in a private conversation with @menzenski. It seems like the issue was that NodeJS v16 and/or Yarn was not available, and was needed because no pre-built wheel was available (because this was being installed directly from source).

Removing the local UI (as planned for Meltano v3) should make building from source/sdist significantly easier.

In the meantime, it appears that the error messages for a failed `yarn` build were not present, which is a bug.

**Comment by menzenski** [comment]
The first time I attempted to install, I did get a Node 16 error message: So I knew to upgrade from my current version (14).

```
...

Building wheels for collected packages: meltano
  Building wheel for meltano (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for meltano (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      0.21.3
      /private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-k5c7dn_3/meltano_bcaf427eeffb42d5962b857ccc5e464f/scripts/build.py:41: Warning: Failed to build Meltano UI webapp: NodeJS v16 is required
        warn(f"{warning_prefix} NodeJS v16 is required", Warning)
      Traceback (most recent call last):
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-build-env-20gdld_s/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-build-env-20gdld_s/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-k5c7dn_3/meltano_bcaf427eeffb42d5962b857ccc5e464f/scripts/build.py", line 93, in custom_build_wheel
          include_webapp()
        File "/private/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pip-install-k5c7dn_3/meltano_bcaf427eeffb42d5962b857ccc5e464f/scripts/build.py", line 52, in include_webapp
          shutil.copy(
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/shutil.py", line 419, in copy
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/Users/matt/.pyenv/versions/3.11.1/lib/python3.11/shutil.py", line 256, in copyfile
          with open(src, 'rb') as fsrc:
               ^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'src/webapp/dist/index.html'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for meltano
Failed to build meltano
ERROR: Could not build wheels for meltano, which is required to install pyproject.toml-based projects
```

**Comment by rawwar** [comment]
> In the meantime, it appears that the error messages for a failed `yarn` build were not present, which is a bug.

Can I just include a subprocess run with the command `yarn --version` and if this fails, we can just raise an exception asking to install yarn? or else, some other action?
