### ISSUE TITLE
bug: Unexpected behaviour from S3 State Backend

### ISSUE THREAD

**Issue by ian-lewis-d** [meltano/meltano#7938]
### Meltano Version

2.19.0

### Python Version

3.8

### Bug scope

API

### Operating System

Mac OS 13.4.1

### Description

Attempting to run a pipeline with S3 State Backend set.

Two strange issues occurred.

1. When I set `MELTANO_STATE_BACKEND_URI='s3://my-data-lake/state/` the files are saved to `s3://my-data-lake/state/state/<env>:<pipeline name>/`  so whatever subdirectory I use in my key is captured and reused as part of the key. It looks like the `/state/` part of my URI is correctly being parsed out as a prefix but is not being removed from the base URI before the request is sent to S3.
2. If I delete the state files or change the URI and attempt to rerun a pipeline the boto3 delete object/retry code seems to b0rk and stops any state being saved. Expected behaviour is a graceful exit or a run with the state saved on S3.
Pipeline run _without_  `--full-refresh` it should just assume it is the first time as there are no state files available at the S3 Backend

For the second case the process stops like this:
```
2023-07-20T16:30:12.135783Z [info     ] Reading state from AWS S3
2023-07-20T16:30:12.149455Z [info     ] Found credentials in environment variables.
2023-07-20T16:30:12.748605Z [error    ] Cannot start plugin tap-mysql: argument of type 'int' is not iterable
2023-07-20T16:30:12.752616Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError("Cannot start plugin tap-mysql: argument of type 'int' is not iterable") exit_codes={} set_number=0 success=False
```

It seems that whatever result is passed back to the tap is not usable and breaks the pipeline.

### Code

```python
1. State Backend S3

.env

MELTANO_STATE_BACKEND_URI='s3://my-data-lake/state/'

Log:

2023-07-21T18:01:30.162987Z [debug    ] Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n\n<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>https://my-data-lake.s3.eu-west-1.amazonaws.com/state%2Fstate%2Fmy-test%3Atap-mysql-to-target-s3%2Fstate.json</Location><Bucket>my-data-lake</Bucket><Key>state/state/my-test:tap-mysql-to-target-s3/state.json</Key><ETag>"e96596dc571d5a2a2193055ec786726f-1"</ETag></CompleteMultipartUploadResult>'
2023-07-21T18:01:30.163329Z [debug    ] Event needs-retry.s3.CompleteMultipartUpload: calling handler <function check_for_200_error at 0x10ab908b0>
2023-07-21T18:01:30.163476Z [debug    ] Event needs-retry.s3.CompleteMultipartUpload: calling handler <botocore.retryhandler.RetryHandler object at 0x10bce0580>
2023-07-21T18:01:30.163608Z [debug    ] No retry needed.
2023-07-21T18:01:30.163712Z [debug    ] Event needs-retry.s3.CompleteMultipartUpload: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x10bce05e0>>
2023-07-21T18:01:30.163874Z [debug    ] smart_open.s3.MultipartWriter('my-data-lake', 'state/state/my-test:tap-mysql-to-target-s3/state.json'): completed multipart upload


2. Attempted (re)run with changed MELTANO_STATE_BACKEND_URI or missing state files and without --full-refresh


2023-07-20T16:31:46.835228Z [debug    ] Event request-created.s3.DeleteObjects: calling handler <function add_retry_headers at 0x110e66a60>
2023-07-20T16:31:46.839799Z [debug    ] Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://my-data-lake.s3.eu-west-1.amazonaws.com/?delete, headers={'User-Agent': b'Boto3/1.28.7 md/Botocore#1.31.7 ua/2.0 os/macos#22.5.0 md/arch#x86_64 lang/python#3.8.16 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.31.7', 'Content-MD5': b'X+**==', 'X-Amz-Date': b'20230720T163146Z', 'X-Amz-Security-Token': b'***Q=', 'X-Amz-Content-SHA256': ****', 'Authorization': b'AWS4-HMAC-SHA256 Credential=**/**/eu-west-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=***', 'amz-sdk-invocation-id': b'***-101c-462e-a487-**', 'amz-sdk-request': b'attempt=1', 'Content-Length': '132'}>
2023-07-20T16:31:46.841607Z [debug    ] Certificate path: /****/venv/lib/python3.8/site-packages/certifi/cacert.pem
2023-07-20T16:31:47.039194Z [debug    ] Response headers: {'x-amz-id-2': 'uG6q8J/Em8uuGjQu4aiK4+****==', 'x-amz-request-id': '*****', 'Date': 'Thu, 20 Jul 2023 16:31:48 GMT', 'Content-Type': 'application/xml', 'Transfer-Encoding': 'chunked', 'Server': 'AmazonS3', 'Connection': 'close'}
2023-07-20T16:31:47.039463Z [debug    ] Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Deleted><Key>/my-test:tap-mysql-to-target-s3/lock</Key><DeleteMarker>true</DeleteMarker><DeleteMarkerVersionId>****</DeleteMarkerVersionId></Deleted></DeleteResult>'
2023-07-20T16:31:47.039996Z [debug    ] Event needs-retry.s3.DeleteObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x111f4ee80>
2023-07-20T16:31:47.040135Z [debug    ] No retry needed.
2023-07-20T16:31:47.040249Z [debug    ] Event needs-retry.s3.DeleteObjects: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x111f4eee0>>
2023-07-20T16:31:47.040900Z [debug    ] Deleted configuration at ****/.meltano/run/tap-mysql/tap.6aaac143-93b4-4bb6-9e6c-d7bd8e086b3b.config.json
2023-07-20T16:31:47.044297Z [error    ] Cannot start plugin tap-mysql: argument of type 'int' is not iterable
2023-07-20T16:31:47.048569Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError("Cannot start plugin tap-mysql: argument of type 'int' is not iterable") exit_codes={} set_number=0 success=False
2023-07-20T16:31:50.147014Z [debug    ] Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Cannot start plugin tap-mysql: argument of type 'int' is not iterable 
Traceback (most recent call last):
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/filesystem.py", line 202, in is_locked
    with self.get_reader(lock_path) as reader:
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/filesystem.py", line 90, in get_reader
    with open(
  File "/****/venv/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 177, in open
    fobj = _shortcut_open(
  File "/****/venv/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/my-test:tap-mysql-to-target-s3/lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/singer.py", line 336, in start
    self.process_handle = await self.invoker.invoke_async(
  File "/****/venv/lib/python3.8/site-packages/meltano/core/plugin_invoker.py", line 443, in invoke_async
    async with self._invoke(*args, **kwargs) as (
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/plugin_invoker.py", line 419, in _invoke
    async with self.plugin.trigger_hooks("invoke", self, args):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 92, in trigger_hooks
    await self.__class__.trigger(self, f"before_{hook_name}", *args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 120, in trigger
    raise err
  File "/****/venv/lib/python3.8/site-packages/meltano/core/behavior/hookable.py", line 112, in trigger
    await hook_func(target, *args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/plugin/singer/tap.py", line 254, in look_up_state_hook
    await self.look_up_state(plugin_invoker)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/plugin/singer/tap.py", line 311, in look_up_state
    state = StateService(
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_service.py", line 158, in get_state
    state = self.state_store_manager.get(state_id=state_id)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/filesystem.py", line 274, in get
    with self.acquire_lock(state_id):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/filesystem.py", line 241, in acquire_lock
    while self.is_locked(state_id):
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/filesystem.py", line 211, in is_locked
    if self.is_file_not_found_error(e):
  File "/****/venv/lib/python3.8/site-packages/meltano/core/state_store/s3.py", line 92, in is_file_not_found_error
    and "NoSuchKey" in err.args[0]
TypeError: argument of type 'int' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/run.py", line 172, in _run_blocks
    await blk.run()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 444, in run
    await self.run_with_job()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 474, in run_with_job
    await self.execute()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 433, in execute
    async with self._start_blocks():
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 563, in _start_blocks
    await block.start()
  File "/****/venv/lib/python3.8/site-packages/meltano/core/block/singer.py", line 343, in start
    raise RunnerError(f"Cannot start plugin {self.string_id}: {err}") from err
meltano.core.runner.RunnerError: Cannot start plugin tap-mysql: argument of type 'int' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/__init__.py", line 105, in _run_cli
    cli(obj={"project": None})
  File "/****/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/cli.py", line 43, in main
    return super().main(*args, windows_expand_args=False, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/utils.py", line 612, in invoke
    super().invoke(ctx)
  File "/****/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/utils.py", line 661, in invoke
    super().invoke(ctx)
  File "/****/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/****/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/params.py", line 27, in decorate
    return func(*args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/params.py", line 76, in decorate
    func(project, *args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/****/venv/lib/python3.8/site-packages/meltano/core/utils/__init__.py", line 79, in wrapper
    return asyncio.run(func(*args, **kwargs))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/run.py", line 141, in run
    raise err
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/run.py", line 138, in run
    await _run_blocks(tracker, parsed_blocks, dry_run=dry_run)
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/run.py", line 184, in _run_blocks
    raise CliError(
meltano.cli.utils.CliError: Run invocation could not be completed as block failed: Cannot start plugin tap-mysql: argument of type 'int' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/****/venv/lib/python3.8/site-packages/meltano/cli/__init__.py", line 115, in _run_cli
    raise CliError(f"{troubleshooting_message}\n{err}") from err
meltano.cli.utils.CliError: Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Cannot start plugin tap-mysql: argument of type 'int' is not iterable
```

**Comment by tayloramurphy** [comment]
@cjohnhanson can you take a look at this? Thanks! cc @seth-meltano

**Comment by WillDaSilva** [comment]
> Meltano Version: 2.1.9

@ian-lewis-d Did you mean `2.19.X`?

**Comment by ian-lewis-d** [comment]
> > Meltano Version: 2.1.9
> 
> @ian-lewis-d Did you mean `2.19.X`?

```
$ meltano --version
meltano, version 2.19.0
```

**Comment by cjohnhanson** [comment]
@ian-lewis-d thanks for reporting! I'll be taking a look at this this week. 

CC: @tayloramurphy

**Comment by edgarrmondragon** [comment]
Another user in Slack reporting this. If the S3 URI is `s3://some_bucket/some/path`, the backend is trying to acquire the lock in `s3://some_bucket/some/path/some/path/my-state-id/lock`.

https://meltano.slack.com/archives/C01TCRBBJD7/p1690310860619849?thread_ts=1690239077.430249&cid=C01TCRBBJD7

**Comment by cjohnhanson** [comment]
CC: @WillDaSilva @edgarrmondragon. 

Found the root cause here. TLDR is that it's a bug in how we parse out the prefix from the backend URI setting and then use it to build the URI and path for reading and writing files--but that bug does not affect how we build the URI and path for _deleting_ files. 

**This should only occur if there's a trailing delimiter in the URI setting value.** 

The fix should be relatively straightforward and for good measure I'll add some new tests for this. 

_But_ I think there's potentially an issue with rolling out a fix. Need to do some more testing to confirm, but I think there feasibly could be users who have been using a trailing delimiter and may not have run into any issues. This means that if we just pushed a bugfix, users may upgrade to a version of Meltano with the bugfix and then their next pipeline run would look for state under the "corrected" path, find none, and do a full refresh. To prevent this we'd need to:
1. Ensure that during upgrade, users migrate their state to the new path by saving state locally before upgrade and then using that locally saved state to set state for each pipeline after the upgrade.
1. Add some band-aid logic within the state management code that checks both the redundant path and the non-redundant path when looking for state.
1. Add some band-aid logic within the upgrade code that checks for state at redundant paths and moves it to the "correct" non-redundant path.

I lean towards option 3, but there may be edge cases or potential pitfalls I'm not thinking of.

**Comment by cjohnhanson** [comment]
@ian-lewis-d heads up that we've identified the root cause and are working towards a fix. But in the meantime, I believe the bug to only be affecting state backend URIs with a trailing `/`; so as a short-term fix I think you should be able to resolve this by removing the trailing `/` from your state backend URI setting.

**Comment by ian-lewis-d** [comment]
Thank you @cjohnhanson - I'll remove the trailing `/` and try again. 

Is there a reason for having the prefix as implicit rather than explicitly set as a config option in `MELTANO_STATE_BACKEND_PREFIX` for example.

**Comment by WillDaSilva** [comment]
@cjohnhanson Thanks for the clear explanation.

> 3. Add some band-aid logic within the upgrade code that checks for state at redundant paths and moves it to the "correct" non-redundant path.
> 
> I lean towards option 3, but there may be edge cases or potential pitfalls I'm not thinking of.

I also lean towards option 3. This is more-or-less the raison d'être of Meltano's upgrade system after all.

**Comment by cjohnhanson** [comment]
@ian-lewis-d heads up that we've merged the fix for this and it will be available in the next Meltano release. We also included logic in the upgrade process so that existing state files under the duplicated prefix will be copied to the non-duplicated equivalent paths.

Apologies for missing this:
> Is there a reason for having the prefix as implicit rather than explicitly set as a config option in MELTANO_STATE_BACKEND_PREFIX for example.

That's a good question. There's not a strong reason for not setting it explicitly, other than consistency of configuration across all state backends and the potential confusion that could be caused by having both a network path in the `MELTANO_STATE_BACKEND_URI` _and_ a prefix, where it might not be immediately clear whether the prefix should be appended to the URI, should replace it always, or should replace it only if the network path and prefix are identical. Adding support for such a setting would be a relatively trivial change, so if you have a strong use case that necessitates it, please feel free to file a follow-on issue for us to consider.

Thanks again for reporting this and for your patience as we get the fix released.
