### ISSUE TITLE
bug: public discovery.yml is throwing 404

### ISSUE THREAD

**Issue by dsuarez692** [meltano/meltano#8481]
### Meltano Version

2.19.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Docker - python:3.10-slim

### Description

My organization uses [tap-postgres--airbyte](https://hub.meltano.com/extractors/tap-postgres--airbyte/), but some days ago it stopped working. Checking the logs I see the error 404 Client Error: Not Found for URL: https://discovery.meltano.com/discovery.yml?project_id=[ProjectID]

### Code

```python
Status: Downloaded newer image for airbyte/source-postgres:latest
Unknown option: discover
2024-04-05T15:32:33.876749Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Cannot start plugin tap-postgres: Catalog discovery failed: command [\'/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte\', \'--config\', \'/home/runner/work/etl/etl/.meltano/run/tap-postgres/tap.d0914042-4782-460a-beeb-d417ab1f6c45.config.json\', \'--discover\'] returned 1 with stderr:\n 2024-04-05 15:32:19,827 | INFO     | tap-airbyte          | Checking for docker on PATH.\n2024-04-05 15:32:19,827 | INFO     | tap-airbyte          | Found docker on PATH.\n2024-04-05 15:32:19,827 | INFO     | tap-airbyte          | Checking docker version.\n2024-04-05 15:32:19,913 | INFO     | tap-airbyte          | Successfully executed docker version.\nTraceback (most recent call last):\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte", line 8, in <module>\n    sys.exit(TapAirbyte.cli())\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main\n    rv = self.invoke(ctx)\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke\n    return __callback(*args, **kwargs)\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 268, in cli\n    tap: TapAirbyte = cls(  # type: ignore\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 110, in __init__\n    self.setup_mapper()\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 180, in setup_mapper\n    self.mapper.register_raw_streams_from_catalog(self.catalog)\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 173, in catalog\n    self._catalog = self.input_catalog or self._singer_catalog\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 326, in _singer_catalog\n    for stream in self.streams.values()\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 135, in streams\n    for stream in self.load_streams():\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 359, in load_streams\n    for stream in self.discover_streams():\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 769, in discover_streams\n    for stream in self.airbyte_catalog["streams"]:\n  File "/home/runner/work/etl/etl/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 654, in airbyte_catalog\n    raise AirbyteException(\ntap_airbyte.tap.AirbyteException: Discover failed with return code 1: Unable to find image \'airbyte/source-postgres:latest\' locally\nlatest: Pulling from airbyte/source-postgres\n47a7782bf367: Pulling fs layer\n6010f22f453f: Pulling fs layer\n78ed1b4fb804: Pulling fs layer\n9ebcf7c62134: Pulling fs layer\n03a51c310f6b: Pulling fs layer\ncdfd99c31e55: Pulling fs layer\n37041fdd7114: Pulling fs layer\n03a51c310f6b: Waiting\ncdfd99c31e55: Waiting\n37041fdd7114: Waiting\n9ebcf7c62134: Waiting\n78ed1b4fb804: Verifying Checksum\n78ed1b4fb804: Download complete\n9ebcf7c62134: Verifying Checksum\n9ebcf7c62134: Download complete\n47a7782bf367: Verifying Checksum\n47a7782bf367: Download complete\ncdfd99c31e55: Verifying Checksum\ncdfd99c31e55: Download complete\n03a51c310f6b: Verifying Checksum\n03a51c310f6b: Download complete\n37041fdd7114: Verifying Checksum\n37041fdd7114: Download complete\n6010f22f453f: Verifying Checksum\n6010f22f453f: Download complete\n47a7782bf367: Pull complete\n6010f22f453f: Pull complete\n78ed1b4fb804: Pull complete\n9ebcf7c62134: Pull complete\n03a51c310f6b: Pull complete\ncdfd99c31e55: Pull complete\n37041fdd7114: Pull complete\nDigest: sha256:c784a3ea8967705d07fac69e6cd7b402754190757221e3df03b6f5b2fcfde107\nStatus: Downloaded newer image for airbyte/source-postgres:latest\nUnknown option: discover\n\n') exit_codes=*** set_number=0 success=False


meltano file
  - name: tap-postgres
    variant: airbyte
    pip_url: git+https://github.com/MeltanoLabs/tap-airbyte-wrapper.git
    config:
      airbyte_config:
        host: [HOST URL]
        port: 5432
        database:[DATABASE NAME]
        username: [DATABASE USERNAME]
        ssl: true
        ssl_mode.mode: prefer
        tunnel_method.tunnel_method: SSH_KEY_AUTH
        tunnel_method.tunnel_host: 
        tunnel_method.tunnel_port: 
        tunnel_method.tunnel_user: 
        replication_method.method: Standard
```

**Comment by edgarrmondragon** [comment]
@dsuarez692 in the meantime, can you try setting the environment variable `MELTANO_DISCOVERY_URL='https://raw.githubusercontent.com/meltano/meltano/v2.19.0/src/meltano/core/bundle/discovery.yml'`?

**Comment by dsuarez692** [comment]
> @dsuarez692 in the meantime, can you try setting the environment variable `MELTANO_DISCOVERY_URL='https://raw.githubusercontent.com/meltano/meltano/v2.19.0/src/meltano/core/bundle/discovery.yml'`?

Same error message 😢

**Comment by edgarrmondragon** [comment]
> > @dsuarez692 in the meantime, can you try setting the environment variable `MELTANO_DISCOVERY_URL='https://raw.githubusercontent.com/meltano/meltano/v2.19.0/src/meltano/core/bundle/discovery.yml'`?
> 
> Same error message 😢

@dsuarez692 I don't know what your environment and workflow looks like so I need to ask: what command did you run and did you make sure that it ran with that environment variable set?

**Comment by dsuarez692** [comment]
> > > @dsuarez692 in the meantime, can you try setting the environment variable `MELTANO_DISCOVERY_URL='https://raw.githubusercontent.com/meltano/meltano/v2.19.0/src/meltano/core/bundle/discovery.yml'`?
> > 
> > 
> > Same error message 😢
> 
> @dsuarez692 I don't know what your environment and workflow looks like so I need to ask: what command did you run and did you make sure that it ran with that environment variable set?

I was able to reproduce it locally. I've created a new Meltano project with tap-postgres-airbyte plugin as the extractor and target-jsonl as the loader. I have a example database running on my local and when I execute 

```
export MELTANO_DISCOVERY_URL='https://raw.githubusercontent.com/meltano/meltano/v2.19.0/src/meltano/core/bundle/discovery.yml'
meltano run tap-postgres target-jsonl
```

I get the same error
`2024-04-05T21:21:32.208010Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Cannot start plugin tap-postgres: Catalog discovery failed: command [\'/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte\', \'--config\', \'/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/run/tap-postgres/tap.ebc47f1c-53ff-476e-84ba-5e1370a1857e.config.json\', \'--discover\'] returned 1 with stderr:\n 2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Checking for docker on PATH.\n2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Found docker on PATH.\n2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Checking docker version.\n2024-04-05 18:21:31,756 | INFO     | tap-airbyte          | Successfully executed docker version.\nTraceback (most recent call last):\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte", line 8, in <module>\n    sys.exit(TapAirbyte.cli())\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main\n    rv = self.invoke(ctx)\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke\n    return __callback(*args, **kwargs)\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 268, in cli\n    tap: TapAirbyte = cls(  # type: ignore\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 110, in __init__\n    self.setup_mapper()\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 180, in setup_mapper\n    self.mapper.register_raw_streams_from_catalog(self.catalog)\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 173, in catalog\n    self._catalog = self.input_catalog or self._singer_catalog\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 326, in _singer_catalog\n    for stream in self.streams.values()\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 135, in streams\n    for stream in self.load_streams():\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 359, in load_streams\n    for stream in self.discover_streams():\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 769, in discover_streams\n    for stream in self.airbyte_catalog["streams"]:\n  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 654, in airbyte_catalog\n    raise AirbyteException(\ntap_airbyte.tap.AirbyteException: Discover failed with return code 1: Unknown option: discover\n\n') exit_codes={} set_number=0 success=False
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Cannot start plugin tap-postgres: Catalog discovery failed: command ['/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte', '--config', '/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/run/tap-postgres/tap.ebc47f1c-53ff-476e-84ba-5e1370a1857e.config.json', '--discover'] returned 1 with stderr:
 2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Checking for docker on PATH.
2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Found docker on PATH.
2024-04-05 18:21:31,673 | INFO     | tap-airbyte          | Checking docker version.
2024-04-05 18:21:31,756 | INFO     | tap-airbyte          | Successfully executed docker version.
Traceback (most recent call last):
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/bin/tap-airbyte", line 8, in <module>
    sys.exit(TapAirbyte.cli())
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 268, in cli
    tap: TapAirbyte = cls(  # type: ignore
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 110, in __init__
    self.setup_mapper()
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 180, in setup_mapper
    self.mapper.register_raw_streams_from_catalog(self.catalog)
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 173, in catalog
    self._catalog = self.input_catalog or self._singer_catalog
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 326, in _singer_catalog
    for stream in self.streams.values()
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 135, in streams
    for stream in self.load_streams():
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/singer_sdk/tap_base.py", line 359, in load_streams
    for stream in self.discover_streams():
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 769, in discover_streams
    for stream in self.airbyte_catalog["streams"]:
  File "/Users/dsuarez/Documents/Code/my-meltano-project/.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py", line 654, in airbyte_catalog
    raise AirbyteException(
tap_airbyte.tap.AirbyteException: Discover failed with return code 1: Unknown option: discover`

**Comment by edgarrmondragon** [comment]
Ah, that's a different error though! I have to run but I'd try tweaking the `capabilities` of the tap in `meltano.yml`. Maybe it doesn't support the `--discover` option?

**Comment by dsuarez692** [comment]
The documentation says that it supports the discover capability, and it was working until two weeks ago. If I remove the discover from the `meltano.yml` file I get this:

`2024-04-05T21:36:35.707578Z [error    ] Cannot start plugin tap-postgres: Applying catalog rules failed: catalog file is missing.
2024-04-05T21:36:35.707861Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Cannot start plugin tap-postgres: Applying catalog rules failed: catalog file is missing.') exit_codes={} set_number=0 success=False
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Cannot start plugin tap-postgres: Applying catalog rules failed: catalog file is missing.`

**Comment by dsuarez692** [comment]
I dug into the code and I found that the line that fails is when the plugin starts a docker image `airbyte/source-postgres:3.3.23, latest` to execute the command `discover`. At that moment, that line throws the error `Unknown option: discover`
Did something change recently on that Docker image?

**Comment by edgarrmondragon** [comment]
> I dug into the code and I found that the line that fails is when the plugin starts a docker image `airbyte/source-postgres:3.3.23, latest` to execute the command `discover`. At that moment, that line throws the error `Unknown option: discover` Did something change recently on that Docker image?

Can't see anything obvious in https://github.com/airbytehq/airbyte/commits/master/airbyte-integrations/connectors/source-postgres that would indicate that 😕

**Comment by dsuarez692** [comment]
I was able to solve it, but sadly I ended up updating the Meltano code 😞 

Inside of `.meltano/extractors/tap-postgres/venv/lib/python3.10/site-packages/tap_airbyte/tap.py` when the code prepares the command to call Docker, the line 372 (`"--",`) is breaking the call. I removed it and it worked again

**Comment by WillDaSilva** [comment]
Thank you for this information @dsuarez692.

This commit seems responsible for adding `"--"` to the command: https://github.com/MeltanoLabs/tap-airbyte-wrapper/commit/e1349aab8c3b338babd0b1de51374733ce68ecb4

I don't understand why the addition of `"--"` would break the command in this way.

**Comment by edgarrmondragon** [comment]
> Thank you for this information @dsuarez692.
> 
> This commit seems responsible for adding `"--"` to the command: [MeltanoLabs/tap-airbyte-wrapper@e1349aa](https://github.com/MeltanoLabs/tap-airbyte-wrapper/commit/e1349aab8c3b338babd0b1de51374733ce68ecb4)
> 
> I don't understand why the addition of `"--"` would break the command in this way.

Yeah, I wonder if it's a problem caused by having an older version of docker.
