### ISSUE TITLE
bug: Meltano marks block as completed and successful even if its still running or an exception has been raised.

### ISSUE THREAD

**Issue by AlejandroUPC** [meltano/meltano#8579]
### Meltano Version

3.4.0

### Python Version

3.11

### Bug scope

Other

### Operating System

debian:bookworm-slim

### Context

We were missing some records from our target, enabling debug logging show that the records were definitely being read but never made it into the target.

We are using:

- `z3-target-bigquery==0.6.8`
- `meltano==3.4.0`

### Issue

When running a LOG_BASED_REPLICATION reading `.bin` files from a MySQL tap, if a Worker is retrying any operation it will declare the run as succesfull before the workers are done.

It seems to assume the process is done:

```
[2024-06-04T08:23:57.011+0000]  INFO - [base] 2024-06-04T08:23:56.979997Z [info     ] 2024-06-04 08:23:56,979 | INFO     | target-bigquery      | Target 'target-bigquery' completed reading 109510 lines of input (109299 records, (0 batch manifests, 130 state messages). 
```

But shortly after adds a worker and some exception is raised (a timeout):

```
[2024-06-04T08:24:41.764+0000]  INFO - [base] 2024-06-04T08:23:56.981168Z [info     ] 2024-06-04 08:23:56,980 | INFO     | target-bigquery      | Adding worker 3d1a265e893042048a55db444bfa7cf0 
[2024-06-04T08:24:41.765+0000]  INFO - [base] 2024-06-04T08:24:41.761751Z [info     ] Exception in thread Thread-1:  
[2024-06-04T08:24:41.766+0000]  INFO - [base] 2024-06-04T08:24:41.762195Z [info     ] Traceback (most recent call last): 
[2024-06-04T08:24:41.766+0000]  INFO - [base] 2024-06-04T08:24:41.762481Z [info     ]   File "-venv/lib/python3.11/site-packages/target_bigquery/batch_job.py", line 61, in run 
[2024-06-04T08:24:41.766+0000]  INFO - [base] 2024-06-04T08:24:41.763205Z [info     ]     ).result()                 
[2024-06-04T08:24:41.767+0000]  INFO - [base] 2024-06-04T08:24:41.763517Z [info     ]       ^^^^^^^^                 
[2024-06-04T08:24:41.767+0000]  INFO - [base] 2024-06-04T08:24:41.763690Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 971, in result 
[2024-06-04T08:24:41.768+0000]  INFO - [base] 2024-06-04T08:24:41.765473Z [info     ]     return super(_AsyncJob, self).result(timeout=timeout, **kwargs) 
[2024-06-04T08:24:41.768+0000]  INFO - [base] 2024-06-04T08:24:41.765886Z [info     ]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.769+0000]  INFO - [base] 2024-06-04T08:24:41.766120Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 256, in result 
[2024-06-04T08:24:41.769+0000]  INFO - [base] 2024-06-04T08:24:41.766591Z [info     ]     self._blocking_poll(timeout=timeout, retry=retry, polling=polling) 
[2024-06-04T08:24:41.769+0000]  INFO - [base] 2024-06-04T08:24:41.766930Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 137, in _blocking_poll 
[2024-06-04T08:24:41.770+0000]  INFO - [base] 2024-06-04T08:24:41.767260Z [info     ]     polling(self._done_or_raise)(retry=retry) 
[2024-06-04T08:24:41.770+0000]  INFO - [base] 2024-06-04T08:24:41.767538Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func 
[2024-06-04T08:24:41.770+0000]  INFO - [base] 2024-06-04T08:24:41.768109Z [info     ]     return retry_target(       
[2024-06-04T08:24:41.771+0000]  INFO - [base] 2024-06-04T08:24:41.768374Z [info     ]            ^^^^^^^^^^^^^       
[2024-06-04T08:24:41.771+0000]  INFO - [base] 2024-06-04T08:24:41.768736Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target 
[2024-06-04T08:24:41.771+0000]  INFO - [base] 2024-06-04T08:24:41.769048Z [info     ]     _retry_error_helper(       
[2024-06-04T08:24:41.772+0000]  INFO - [base] 2024-06-04T08:24:41.769268Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper 
[2024-06-04T08:24:41.772+0000]  INFO - [base] 2024-06-04T08:24:41.769608Z [info     ]     raise final_exc from source_exc 
[2024-06-04T08:24:41.772+0000]  INFO - [base] 2024-06-04T08:24:41.769975Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target 
[2024-06-04T08:24:41.772+0000]  INFO - [base] 2024-06-04T08:24:41.770223Z [info     ]     result = target()          
[2024-06-04T08:24:41.772+0000]  INFO - [base] 2024-06-04T08:24:41.770563Z [info     ]              ^^^^^^^^          
[2024-06-04T08:24:41.773+0000]  INFO - [base] 2024-06-04T08:24:41.770749Z [info     ]   File "-venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 119, in _done_or_raise 
[2024-06-04T08:24:41.773+0000]  INFO - [base] 2024-06-04T08:24:41.771086Z [info     ]     if not self.done(retry=retry): 
[2024-06-04T08:24:41.773+0000]  INFO - [base] 2024-06-04T08:24:41.771380Z [info     ]            ^^^^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.774+0000]  INFO - [base] 2024-06-04T08:24:41.771664Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 938, in done 
[2024-06-04T08:24:41.774+0000]  INFO - [base] 2024-06-04T08:24:41.771900Z [info     ]     self.reload(retry=retry, timeout=timeout) 
[2024-06-04T08:24:41.774+0000]  INFO - [base] 2024-06-04T08:24:41.772180Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 828, in reload 
[2024-06-04T08:24:41.774+0000]  INFO - [base] 2024-06-04T08:24:41.772452Z [info     ]     api_response = client._call_api( 
[2024-06-04T08:24:41.775+0000]  INFO - [base] 2024-06-04T08:24:41.772767Z [info     ]                    ^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.775+0000]  INFO - [base] 2024-06-04T08:24:41.773109Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api 
[2024-06-04T08:24:41.775+0000]  INFO - [base] 2024-06-04T08:24:41.773515Z [info     ]     return call()              
[2024-06-04T08:24:41.776+0000]  INFO - [base] 2024-06-04T08:24:41.773705Z [info     ]            ^^^^^^              
[2024-06-04T08:24:41.776+0000]  INFO - [base] 2024-06-04T08:24:41.773995Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/_http/__init__.py", line 482, in api_request 
[2024-06-04T08:24:41.776+0000]  INFO - [base] 2024-06-04T08:24:41.774268Z [info     ]     response = self._make_request( 
[2024-06-04T08:24:41.777+0000]  INFO - [base] 2024-06-04T08:24:41.774455Z [info     ]                ^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.777+0000]  INFO - [base] 2024-06-04T08:24:41.774677Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request 
[2024-06-04T08:24:41.777+0000]  INFO - [base] 2024-06-04T08:24:41.774832Z [info     ]     return self._do_request(   
[2024-06-04T08:24:41.778+0000]  INFO - [base] 2024-06-04T08:24:41.775107Z [info     ]            ^^^^^^^^^^^^^^^^^   
[2024-06-04T08:24:41.778+0000]  INFO - [base] 2024-06-04T08:24:41.775327Z [info     ]   File "-venv/lib/python3.11/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request 
[2024-06-04T08:24:41.778+0000]  INFO - [base] 2024-06-04T08:24:41.775659Z [info     ]     return self.http.request(  
[2024-06-04T08:24:41.778+0000]  INFO - [base] 2024-06-04T08:24:41.775896Z [info     ]            ^^^^^^^^^^^^^^^^^^  
[2024-06-04T08:24:41.779+0000]  INFO - [base] 2024-06-04T08:24:41.776188Z [info     ]   File "-venv/lib/python3.11/site-packages/google/auth/transport/requests.py", line 541, in request 
[2024-06-04T08:24:41.779+0000]  INFO - [base] 2024-06-04T08:24:41.776454Z [info     ]     response = super(AuthorizedSession, self).request( 
[2024-06-04T08:24:41.779+0000]  INFO - [base] 2024-06-04T08:24:41.776739Z [info     ]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.779+0000]  INFO - [base] 2024-06-04T08:24:41.777077Z [info     ]   File "-venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request 
[2024-06-04T08:24:41.779+0000]  INFO - [base] 2024-06-04T08:24:41.777388Z [info     ]     resp = self.send(prep, **send_kwargs) 
[2024-06-04T08:24:41.780+0000]  INFO - [base] 2024-06-04T08:24:41.777667Z [info     ]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.780+0000]  INFO - [base] 2024-06-04T08:24:41.777904Z [info     ]   File "-venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send 
[2024-06-04T08:24:41.780+0000]  INFO - [base] 2024-06-04T08:24:41.778277Z [info     ]     r = adapter.send(request, **kwargs) 
[2024-06-04T08:24:41.780+0000]  INFO - [base] 2024-06-04T08:24:41.778564Z [info     ]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
[2024-06-04T08:24:41.781+0000]  INFO - [base] 2024-06-04T08:24:41.778864Z [info     ]   File "-venv/lib/python3.11/site-packages/requests/adapters.py", line 682, in send 
[2024-06-04T08:24:41.781+0000]  INFO - [base] 2024-06-04T08:24:41.779470Z [info     ]     raise ConnectionError(err, request=request) 
[2024-06-04T08:24:41.781+0000]  INFO - [base] 2024-06-04T08:24:41.779827Z [info     ] requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 
[2024-06-04T08:24:41.782+0000]  INFO - [base] 2024-06-04T08:24:41.780169Z [info     ]                                
[2024-06-04T08:24:41.783+0000]  INFO - [base] 2024-06-04T08:24:41.780431Z [info     ] During handling of the above exception, another exception occurred: 
[2024-06-04T08:24:41.783+0000]  INFO - [base] 2024-06-04T08:24:41.780730Z [info     ]                                
[2024-06-04T08:24:41.783+0000]  INFO - [base] 2024-06-04T08:24:41.781014Z [info     ] Traceback (most recent call last): 
[2024-06-04T08:24:41.783+0000]  INFO - [base] 2024-06-04T08:24:41.781281Z [info     ]   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner 
[2024-06-04T08:24:41.784+0000]  INFO - [base] 2024-06-04T08:24:41.781629Z [info     ]     self.run()                 
[2024-06-04T08:24:41.784+0000]  INFO - [base] 2024-06-04T08:24:41.781884Z [info     ]   File "-venv/lib/python3.11/site-packages/target_bigquery/batch_job.py", line 63, in run 
[2024-06-04T08:24:41.784+0000]  INFO - [base] 2024-06-04T08:24:41.782183Z [info     ]     job.attempt += 1           
[2024-06-04T08:24:41.784+0000]  INFO - [base] 2024-06-04T08:24:41.782458Z [info     ]     ^^^^^^^^^^^           
```

And it will finally emit the message as the tap was succesfully completed:

```
[2024-06-04T08:24:41.874+0000]  INFO - [base] 2024-06-04T08:24:41.783388Z [info     ] 2024-06-04 08:24:41,782 | INFO     | target-bigquery      | Emitting completed target state {"currently_syncing": null, ...} 
[2024-06-04T08:24:43.323+0000]  INFO - [base] 2024-06-04T08:24:42.314062Z [info     ] Block run completed.           block_type=ExtractLoadBlocks err=None set_number=0 success=True 
[2024-06-04T08:24:43.323+0000] INFO - [base] 2024-06-04T08:24:42.314062Z [info     ] Block run completed.           block_type=ExtractLoadBlocks err=None set_number=0 success=True
``` 

We fail to understand the following:

1. Why is the exception and the consequent messages logged at an INFO level?
2. It looks like the process is not really looking if the queue is empty when emiting the completed message?
3. Is it an expected behavior to let the run complete even if we defined `fail_fast: true`.

**Comment by edgarrmondragon** [comment]
Another user running into a similar issue: https://meltano.slack.com/archives/C069CQNHDNF/p1725563405822319.

<blockquote>

I'm having some issues with a stream that I'm using -> Basically, it's a fairly large API call (large return file), and I'm receiving the following message:

```
Target sink for 'timelogs' is full. Draining... cmd_type=elb consumer=True job_name=prod:X producer=False run_id=d5e7c790-991a-403a-a26b-4c2e1a36ffbb stdio=stderr string_id=Y
Culling terminated worker a7a32ae89fc3478487dd7b80cd756d63 cmd_type=elb consumer=True job_name=X run_id=d5e7c790-991a-403a-a26b-4c2e1a36ffbb stdio=stderr string_id=Y
```

Then airflow marks the task as failed.
Has anyone ever experienced this issue? What could I do to resolve it? Currently, I'm considering reducing the load batch size, but woould love some input! (edited) 

</blockquote>

Again, using https://github.com/z3z1ma/target-bigquery.

**Comment by SBurwash** [comment]
@edgarrmondragon what is your level of support for the bigquery loader?

**Comment by edgarrmondragon** [comment]
"Official" support is in the backlog but won't be prioritized soon enough I think. I'd support community efforts for a MeltanoLabs/target-bigquery, and help with triage and housekeeping of it if there's interest.

**Comment by AlejandroUPC** [comment]
Hello @SBurwash , are you referring to this specific loader I mentioned in my issue? If so the maintainer himself is quite active and I have a few MR's on their repo, so feel free to open one there and let me know.
