### ISSUE TITLE
bug: Handle non-unicode characaters in plugin logs

### ISSUE THREAD

**Issue by stephanbertl** [meltano/meltano#8799]
### Meltano Version

3.5.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows 11 - pwsh

### Description

running tap-mssql to target-csv

records with non-ascii characters ("самых"), pipeline runs but the logging throws errors:

```
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 124-126: character maps to <undefined>
Call stack:
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\<user>\.local\bin\meltano.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\__init__.py", line 124, in main
    _run_cli()
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\__init__.py", line 103, in _run_cli
    cli(obj={"project": None})
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\cli.py", line 46, in main
    return super().main(*args, windows_expand_args=False, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\utils.py", line 662, in invoke
    super().invoke(ctx)  # type: ignore[misc]
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\utils.py", line 711, in invoke
    super().invoke(ctx)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\params.py", line 74, in decorate
    return func(*args, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\cli\params.py", line 164, in decorate
    func(project, *args, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\core\utils\__init__.py", line 73, in wrapper
    return asyncio.run(func(*args, **kwargs))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\core\logging\utils.py", line 230, in capture_subprocess_output
    if not await _write_line_writer(writer, line):
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\core\logging\utils.py", line 201, in _write_line_writer
    writer.writeline(line.decode(errors="replace"))
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\meltano\core\logging\output_logger.py", line 271, in writeline
    self.logger.log(self.write_level, line.rstrip(), name=self.name)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\structlog\stdlib.py", line 237, in log
    return self._proxy_to_logger(LEVEL_TO_NAME[level], event, *args, **kw)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\structlog\stdlib.py", line 258, in _proxy_to_logger
    return super()._proxy_to_logger(method_name, event=event, **event_kw)
  File "C:\Users\<user>\pipx\venvs\meltano\lib\site-packages\structlog\_base.py", line 215, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
Message: {'consumer': False, 'producer': True, 'string_id': 'tap-mssql--ap', 'cmd_type': 'elb', 'run_id': 'de7cd47c-a1ea-4dcb-93e1-c1503efd5c3b', 'job_name': 'local:tap-mssql--ap-to-target-csv', 'stdio': 'stdout', 'name': 'tap-mssql--ap', 'event': '{"type":"RECORD","stream": ---REDACTED--- entry: "самых" ---REDACTED---   ,"version":1727252247132,"time_extracted":"2024-09-25T08:17:27.166450Z"}', 'level': 'info', 'timestamp': '2024-09-25T08:17:30.369830Z'}
```

**Comment by edgarrmondragon** [comment]
Hi @stephanbertl!

Thanks for reporting, just to confirm: is this something that prevents your pipelines from working? It's obviously a nuisance, but I'm trying to set a priority for this.

Otherwise I'm opening this up for contributions if someone's motivated to fix it themselves. One avenue you could explore is adding [`structlog.processors.UnicodeEncoder`](https://www.structlog.org/en/stable/api.html#structlog.processors.UnicodeEncoder) to the default processor chain:

https://github.com/meltano/meltano/blob/357ab392b80aac9a9fd513234b41f95ec1046c24/src/meltano/core/logging/utils.py#L148-L154

**Comment by stephanbertl** [comment]
@edgarrmondragon this one isnt breaking the pipeline directly. It just spams the logs.

(I might open another unicode related issue, although I am unsure if the tap or meltano itself is the culprit. When pulling from tap-mssql and moving data to target iceberg, somewhere in the chain the unicode breaks and surrogate characters show up.)

**Comment by edgarrmondragon** [comment]
@stephanbertl I believe you're running with the `--log-level=debug` option and that's why these non-unicode RECORD fields are causing issues in the logging system? One way to disable if you don't need them to show up in the console is with something like https://github.com/meltano/meltano/issues/8760 (see https://docs.meltano.com/guide/logging/).
